-- ========================================================
-- CLEAN ALL TEST DATA - SAFE VERSION
-- Deletes all data while keeping schema intact.
-- Run: psql -d your_database -f clean_test_data.sql
-- ========================================================

BEGIN;

-- Clear in dependency order (children first, then parents)
TRUNCATE TABLE IF EXISTS user_fcm_tokens CASCADE;
TRUNCATE TABLE IF EXISTS user_preferences CASCADE;
TRUNCATE TABLE IF EXISTS privacy_settings CASCADE;
TRUNCATE TABLE IF EXISTS notification_settings CASCADE;
TRUNCATE TABLE IF EXISTS notifications CASCADE;
TRUNCATE TABLE IF EXISTS profile_views CASCADE;
TRUNCATE TABLE IF EXISTS message_reactions CASCADE;
TRUNCATE TABLE IF EXISTS messages CASCADE;
TRUNCATE TABLE IF EXISTS story_views CASCADE;
TRUNCATE TABLE IF EXISTS story_reactions CASCADE;
TRUNCATE TABLE IF EXISTS story_mentions CASCADE;
TRUNCATE TABLE IF EXISTS archived_stories CASCADE;
TRUNCATE TABLE IF EXISTS highlight_stories CASCADE;
TRUNCATE TABLE IF EXISTS highlights CASCADE;
TRUNCATE TABLE IF EXISTS stories CASCADE;
TRUNCATE TABLE IF EXISTS post_comments CASCADE;
TRUNCATE TABLE IF EXISTS post_likes CASCADE;
TRUNCATE TABLE IF EXISTS saved_posts CASCADE;
TRUNCATE TABLE IF EXISTS posts CASCADE;
TRUNCATE TABLE IF EXISTS reel_comments CASCADE;
TRUNCATE TABLE IF EXISTS reel_likes CASCADE;
TRUNCATE TABLE IF EXISTS saved_reels CASCADE;
TRUNCATE TABLE IF EXISTS reel_saves CASCADE;
TRUNCATE TABLE IF EXISTS reels CASCADE;
TRUNCATE TABLE IF EXISTS connections CASCADE;
TRUNCATE TABLE IF EXISTS crossings CASCADE;
TRUNCATE TABLE IF EXISTS locations CASCADE;
TRUNCATE TABLE IF EXISTS group_messages CASCADE;
TRUNCATE TABLE IF EXISTS group_members CASCADE;
TRUNCATE TABLE IF EXISTS groups CASCADE;
TRUNCATE TABLE IF EXISTS reports CASCADE;
TRUNCATE TABLE IF EXISTS user_blocks CASCADE;
TRUNCATE TABLE IF EXISTS blocked_users CASCADE;
TRUNCATE TABLE IF EXISTS username_history CASCADE;
TRUNCATE TABLE IF EXISTS reserved_usernames CASCADE;
TRUNCATE TABLE IF EXISTS user_badges CASCADE;
TRUNCATE TABLE IF EXISTS user_streaks CASCADE;
TRUNCATE TABLE IF EXISTS daily_stats CASCADE;
TRUNCATE TABLE IF EXISTS activity_logs CASCADE;
TRUNCATE TABLE IF EXISTS user_activity_logs CASCADE;
TRUNCATE TABLE IF EXISTS engagement_events CASCADE;
TRUNCATE TABLE IF EXISTS support_tickets CASCADE;
TRUNCATE TABLE IF EXISTS data_export_jobs CASCADE;
TRUNCATE TABLE IF EXISTS fcm_tokens CASCADE;
TRUNCATE TABLE IF EXISTS sessions CASCADE;
TRUNCATE TABLE IF EXISTS password_resets CASCADE;
TRUNCATE TABLE IF EXISTS email_verifications CASCADE;
TRUNCATE TABLE IF EXISTS phone_verifications CASCADE;
TRUNCATE TABLE IF EXISTS users CASCADE;

COMMIT;
