// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createUserAuditLog = `-- name: CreateUserAuditLog :one
INSERT INTO user_activity_logs (
    user_id, action, details, ip_address, user_agent
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, action, details, ip_address, user_agent, created_at
`

type CreateUserAuditLogParams struct {
	UserID    uuid.UUID             `json:"user_id"`
	Action    string                `json:"action"`
	Details   pqtype.NullRawMessage `json:"details"`
	IpAddress sql.NullString        `json:"ip_address"`
	UserAgent sql.NullString        `json:"user_agent"`
}

func (q *Queries) CreateUserAuditLog(ctx context.Context, arg CreateUserAuditLogParams) (UserActivityLog, error) {
	row := q.db.QueryRowContext(ctx, createUserAuditLog,
		arg.UserID,
		arg.Action,
		arg.Details,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i UserActivityLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.Details,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLogsByAction = `-- name: GetAuditLogsByAction :many
SELECT id, user_id, action, details, ip_address, user_agent, created_at FROM user_activity_logs
WHERE action = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetAuditLogsByActionParams struct {
	Action string `json:"action"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetAuditLogsByAction(ctx context.Context, arg GetAuditLogsByActionParams) ([]UserActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, getAuditLogsByAction, arg.Action, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserActivityLog
	for rows.Next() {
		var i UserActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAuditLogs = `-- name: GetUserAuditLogs :many
SELECT id, user_id, action, details, ip_address, user_agent, created_at FROM user_activity_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserAuditLogsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetUserAuditLogs(ctx context.Context, arg GetUserAuditLogsParams) ([]UserActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, getUserAuditLogs, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserActivityLog
	for rows.Next() {
		var i UserActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
