// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    name,
    slug,
    icon,
    color,
    is_active
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, name, slug, icon, color, is_active, created_at
`

type CreateCategoryParams struct {
	Name     string         `json:"name"`
	Slug     string         `json:"slug"`
	Icon     sql.NullString `json:"icon"`
	Color    sql.NullString `json:"color"`
	IsActive bool           `json:"is_active"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.Name,
		arg.Slug,
		arg.Icon,
		arg.Color,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, slug, icon, color, is_active, created_at FROM categories
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCategory(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug, icon, color, is_active, created_at FROM categories
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const incrementCategoryStats = `-- name: IncrementCategoryStats :exec
INSERT INTO category_stats (
    category_id, posts_count, reels_count, stories_count
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (category_id) DO UPDATE
SET
    posts_count = category_stats.posts_count + EXCLUDED.posts_count,
    reels_count = category_stats.reels_count + EXCLUDED.reels_count,
    stories_count = category_stats.stories_count + EXCLUDED.stories_count,
    updated_at = now()
`

type IncrementCategoryStatsParams struct {
	CategoryID   uuid.UUID `json:"category_id"`
	PostsCount   int32     `json:"posts_count"`
	ReelsCount   int32     `json:"reels_count"`
	StoriesCount int32     `json:"stories_count"`
}

func (q *Queries) IncrementCategoryStats(ctx context.Context, arg IncrementCategoryStatsParams) error {
	_, err := q.db.ExecContext(ctx, incrementCategoryStats,
		arg.CategoryID,
		arg.PostsCount,
		arg.ReelsCount,
		arg.StoriesCount,
	)
	return err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, icon, color, is_active, created_at FROM categories
WHERE is_active = true
ORDER BY name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Icon,
			&i.Color,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrendingCategories = `-- name: ListTrendingCategories :many
SELECT c.id, c.name, c.slug, c.icon, c.color, c.is_active, c.created_at, s.posts_count, s.reels_count, s.stories_count
FROM categories c
JOIN category_stats s ON c.id = s.category_id
WHERE c.is_active = true
ORDER BY (s.posts_count + s.reels_count + s.stories_count) DESC
LIMIT $1 OFFSET $2
`

type ListTrendingCategoriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListTrendingCategoriesRow struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Icon         sql.NullString `json:"icon"`
	Color        sql.NullString `json:"color"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	PostsCount   int32          `json:"posts_count"`
	ReelsCount   int32          `json:"reels_count"`
	StoriesCount int32          `json:"stories_count"`
}

func (q *Queries) ListTrendingCategories(ctx context.Context, arg ListTrendingCategoriesParams) ([]ListTrendingCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTrendingCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrendingCategoriesRow
	for rows.Next() {
		var i ListTrendingCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Icon,
			&i.Color,
			&i.IsActive,
			&i.CreatedAt,
			&i.PostsCount,
			&i.ReelsCount,
			&i.StoriesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name = COALESCE($1, name),
    slug = COALESCE($2, slug),
    icon = COALESCE($3, icon),
    color = COALESCE($4, color),
    is_active = COALESCE($5, is_active)
WHERE id = $6
RETURNING id, name, slug, icon, color, is_active, created_at
`

type UpdateCategoryParams struct {
	Name     sql.NullString `json:"name"`
	Slug     sql.NullString `json:"slug"`
	Icon     sql.NullString `json:"icon"`
	Color    sql.NullString `json:"color"`
	IsActive sql.NullBool   `json:"is_active"`
	ID       uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.Name,
		arg.Slug,
		arg.Icon,
		arg.Color,
		arg.IsActive,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
