// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    name,
    slug,
    icon,
    color,
    is_active
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, name, slug, icon, color, is_active, created_at
`

type CreateCategoryParams struct {
	Name     string         `json:"name"`
	Slug     string         `json:"slug"`
	Icon     sql.NullString `json:"icon"`
	Color    sql.NullString `json:"color"`
	IsActive bool           `json:"is_active"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.Name,
		arg.Slug,
		arg.Icon,
		arg.Color,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, slug, icon, color, is_active, created_at FROM categories
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCategory(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug, icon, color, is_active, created_at FROM categories
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const incrementCategoryStats = `-- name: IncrementCategoryStats :exec
INSERT INTO category_stats (
    category_id, posts_count, reels_count, stories_count
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (category_id) DO UPDATE
SET
    posts_count = category_stats.posts_count + EXCLUDED.posts_count,
    reels_count = category_stats.reels_count + EXCLUDED.reels_count,
    stories_count = category_stats.stories_count + EXCLUDED.stories_count,
    updated_at = now()
`

type IncrementCategoryStatsParams struct {
	CategoryID   uuid.UUID `json:"category_id"`
	PostsCount   int32     `json:"posts_count"`
	ReelsCount   int32     `json:"reels_count"`
	StoriesCount int32     `json:"stories_count"`
}

func (q *Queries) IncrementCategoryStats(ctx context.Context, arg IncrementCategoryStatsParams) error {
	_, err := q.db.ExecContext(ctx, incrementCategoryStats,
		arg.CategoryID,
		arg.PostsCount,
		arg.ReelsCount,
		arg.StoriesCount,
	)
	return err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, icon, color, is_active, created_at FROM categories
WHERE is_active = true
ORDER BY name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Icon,
			&i.Color,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryCreators = `-- name: ListCategoryCreators :many
SELECT u.id, u.username, u.full_name, u.avatar_url, u.is_verified, u.bio,
       COUNT(DISTINCT p.id) + COUNT(DISTINCT r.id) AS content_count
FROM users u
LEFT JOIN posts p ON p.user_id = u.id AND p.category_id = $3
LEFT JOIN reels r ON r.user_id = u.id AND r.category_id = $3
WHERE u.is_shadow_banned = false
GROUP BY u.id, u.username, u.full_name, u.avatar_url, u.is_verified, u.bio
HAVING COUNT(DISTINCT p.id) + COUNT(DISTINCT r.id) > 0
ORDER BY content_count DESC
LIMIT $1 OFFSET $2
`

type ListCategoryCreatorsParams struct {
	Limit      int32         `json:"limit"`
	Offset     int32         `json:"offset"`
	CategoryID uuid.NullUUID `json:"category_id"`
}

type ListCategoryCreatorsRow struct {
	ID           uuid.UUID      `json:"id"`
	Username     string         `json:"username"`
	FullName     string         `json:"full_name"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	IsVerified   bool           `json:"is_verified"`
	Bio          sql.NullString `json:"bio"`
	ContentCount int32          `json:"content_count"`
}

func (q *Queries) ListCategoryCreators(ctx context.Context, arg ListCategoryCreatorsParams) ([]ListCategoryCreatorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategoryCreators, arg.Limit, arg.Offset, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoryCreatorsRow
	for rows.Next() {
		var i ListCategoryCreatorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.IsVerified,
			&i.Bio,
			&i.ContentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryPosts = `-- name: ListCategoryPosts :many
SELECT p.id, p.user_id, p.media_url, p.media_type, p.caption, p.body_text, p.location_name, p.crop_settings, p.category_id,
       p.likes_count, p.comments_count, p.shares_count, p.created_at, p.updated_at,
       u.username, u.full_name, u.avatar_url,
       CASE WHEN p.geom IS NOT NULL THEN ST_Y(p.geom::geometry) ELSE NULL END as lat_out,
       CASE WHEN p.geom IS NOT NULL THEN ST_X(p.geom::geometry) ELSE NULL END as lng_out,
       EXISTS(SELECT 1 FROM post_likes pl WHERE pl.post_id = p.id AND pl.user_id = $1) as liked_by_viewer,
       EXISTS(SELECT 1 FROM post_saves ps WHERE ps.post_id = p.id AND ps.user_id = $1) as is_saved
FROM posts p
JOIN users u ON p.user_id = u.id
WHERE p.category_id = $2
  AND u.is_shadow_banned = false
ORDER BY p.created_at DESC
LIMIT $4 OFFSET $3
`

type ListCategoryPostsParams struct {
	ViewerID   uuid.UUID     `json:"viewer_id"`
	CategoryID uuid.NullUUID `json:"category_id"`
	Off        int32         `json:"off"`
	Lim        int32         `json:"lim"`
}

type ListCategoryPostsRow struct {
	ID            uuid.UUID             `json:"id"`
	UserID        uuid.UUID             `json:"user_id"`
	MediaUrl      string                `json:"media_url"`
	MediaType     string                `json:"media_type"`
	Caption       sql.NullString        `json:"caption"`
	BodyText      sql.NullString        `json:"body_text"`
	LocationName  sql.NullString        `json:"location_name"`
	CropSettings  pqtype.NullRawMessage `json:"crop_settings"`
	CategoryID    uuid.NullUUID         `json:"category_id"`
	LikesCount    int32                 `json:"likes_count"`
	CommentsCount int32                 `json:"comments_count"`
	SharesCount   int32                 `json:"shares_count"`
	CreatedAt     time.Time             `json:"created_at"`
	UpdatedAt     time.Time             `json:"updated_at"`
	Username      string                `json:"username"`
	FullName      string                `json:"full_name"`
	AvatarUrl     sql.NullString        `json:"avatar_url"`
	LatOut        interface{}           `json:"lat_out"`
	LngOut        interface{}           `json:"lng_out"`
	LikedByViewer bool                  `json:"liked_by_viewer"`
	IsSaved       bool                  `json:"is_saved"`
}

func (q *Queries) ListCategoryPosts(ctx context.Context, arg ListCategoryPostsParams) ([]ListCategoryPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategoryPosts,
		arg.ViewerID,
		arg.CategoryID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoryPostsRow
	for rows.Next() {
		var i ListCategoryPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Caption,
			&i.BodyText,
			&i.LocationName,
			&i.CropSettings,
			&i.CategoryID,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.LatOut,
			&i.LngOut,
			&i.LikedByViewer,
			&i.IsSaved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryReels = `-- name: ListCategoryReels :many
SELECT r.id, r.user_id, r.video_url, r.caption, r.is_ai_generated, r.location_name, r.geohash, r.category_id,
       COALESCE(ST_Y(r.geom::geometry)::float8, 0.0)::float8 AS lat, COALESCE(ST_X(r.geom::geometry)::float8, 0.0)::float8 AS lng,
       r.likes_count, r.comments_count, r.shares_count, r.saves_count, r.created_at, r.updated_at,
       u.username, u.avatar_url,
       EXISTS (SELECT 1 FROM reel_likes rl WHERE rl.reel_id = r.id AND rl.user_id = $3) AS is_liked,
       EXISTS (SELECT 1 FROM reel_saves rs WHERE rs.reel_id = r.id AND rs.user_id = $3) AS is_saved,
       COALESCE((SELECT status FROM connections c WHERE (c.requester_id = $3 AND c.target_id = r.user_id) OR (c.requester_id = r.user_id AND c.target_id = $3) LIMIT 1)::text, 'none') AS connection_status
FROM reels r
JOIN users u ON r.user_id = u.id
WHERE r.category_id = $4
  AND u.is_shadow_banned = false
ORDER BY r.created_at DESC
LIMIT $1 OFFSET $2
`

type ListCategoryReelsParams struct {
	Limit      int32         `json:"limit"`
	Offset     int32         `json:"offset"`
	ViewerID   uuid.UUID     `json:"viewer_id"`
	CategoryID uuid.NullUUID `json:"category_id"`
}

type ListCategoryReelsRow struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	VideoUrl         string         `json:"video_url"`
	Caption          sql.NullString `json:"caption"`
	IsAiGenerated    bool           `json:"is_ai_generated"`
	LocationName     sql.NullString `json:"location_name"`
	Geohash          sql.NullString `json:"geohash"`
	CategoryID       uuid.NullUUID  `json:"category_id"`
	Lat              float64        `json:"lat"`
	Lng              float64        `json:"lng"`
	LikesCount       int32          `json:"likes_count"`
	CommentsCount    int32          `json:"comments_count"`
	SharesCount      int32          `json:"shares_count"`
	SavesCount       int32          `json:"saves_count"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	Username         string         `json:"username"`
	AvatarUrl        sql.NullString `json:"avatar_url"`
	IsLiked          bool           `json:"is_liked"`
	IsSaved          bool           `json:"is_saved"`
	ConnectionStatus interface{}    `json:"connection_status"`
}

func (q *Queries) ListCategoryReels(ctx context.Context, arg ListCategoryReelsParams) ([]ListCategoryReelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategoryReels,
		arg.Limit,
		arg.Offset,
		arg.ViewerID,
		arg.CategoryID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoryReelsRow
	for rows.Next() {
		var i ListCategoryReelsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VideoUrl,
			&i.Caption,
			&i.IsAiGenerated,
			&i.LocationName,
			&i.Geohash,
			&i.CategoryID,
			&i.Lat,
			&i.Lng,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.SavesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AvatarUrl,
			&i.IsLiked,
			&i.IsSaved,
			&i.ConnectionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrendingCategories = `-- name: ListTrendingCategories :many
SELECT c.id, c.name, c.slug, c.icon, c.color, c.is_active, c.created_at, s.posts_count, s.reels_count, s.stories_count
FROM categories c
JOIN category_stats s ON c.id = s.category_id
WHERE c.is_active = true
ORDER BY (s.posts_count + s.reels_count + s.stories_count) DESC
LIMIT $1 OFFSET $2
`

type ListTrendingCategoriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListTrendingCategoriesRow struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Icon         sql.NullString `json:"icon"`
	Color        sql.NullString `json:"color"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	PostsCount   int32          `json:"posts_count"`
	ReelsCount   int32          `json:"reels_count"`
	StoriesCount int32          `json:"stories_count"`
}

func (q *Queries) ListTrendingCategories(ctx context.Context, arg ListTrendingCategoriesParams) ([]ListTrendingCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTrendingCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrendingCategoriesRow
	for rows.Next() {
		var i ListTrendingCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Icon,
			&i.Color,
			&i.IsActive,
			&i.CreatedAt,
			&i.PostsCount,
			&i.ReelsCount,
			&i.StoriesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name = COALESCE($1, name),
    slug = COALESCE($2, slug),
    icon = COALESCE($3, icon),
    color = COALESCE($4, color),
    is_active = COALESCE($5, is_active)
WHERE id = $6
RETURNING id, name, slug, icon, color, is_active, created_at
`

type UpdateCategoryParams struct {
	Name     sql.NullString `json:"name"`
	Slug     sql.NullString `json:"slug"`
	Icon     sql.NullString `json:"icon"`
	Color    sql.NullString `json:"color"`
	IsActive sql.NullBool   `json:"is_active"`
	ID       uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.Name,
		arg.Slug,
		arg.Icon,
		arg.Color,
		arg.IsActive,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
