// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: data_export.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDataExportJob = `-- name: CreateDataExportJob :one
INSERT INTO data_export_jobs (
    user_id, status
) VALUES (
    $1, 'pending'
) RETURNING id, user_id, status, file_path, expires_at, error_message, created_at, updated_at
`

func (q *Queries) CreateDataExportJob(ctx context.Context, userID uuid.UUID) (DataExportJob, error) {
	row := q.db.QueryRowContext(ctx, createDataExportJob, userID)
	var i DataExportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.FilePath,
		&i.ExpiresAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDataExportJob = `-- name: GetDataExportJob :one
SELECT id, user_id, status, file_path, expires_at, error_message, created_at, updated_at FROM data_export_jobs WHERE id = $1
`

func (q *Queries) GetDataExportJob(ctx context.Context, id uuid.UUID) (DataExportJob, error) {
	row := q.db.QueryRowContext(ctx, getDataExportJob, id)
	var i DataExportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.FilePath,
		&i.ExpiresAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestDataExportJob = `-- name: GetLatestDataExportJob :one
SELECT id, user_id, status, file_path, expires_at, error_message, created_at, updated_at FROM data_export_jobs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestDataExportJob(ctx context.Context, userID uuid.UUID) (DataExportJob, error) {
	row := q.db.QueryRowContext(ctx, getLatestDataExportJob, userID)
	var i DataExportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.FilePath,
		&i.ExpiresAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDataExportJob = `-- name: UpdateDataExportJob :one
UPDATE data_export_jobs
SET status = $2, file_path = $3, expires_at = $4, error_message = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, status, file_path, expires_at, error_message, created_at, updated_at
`

type UpdateDataExportJobParams struct {
	ID           uuid.UUID      `json:"id"`
	Status       string         `json:"status"`
	FilePath     sql.NullString `json:"file_path"`
	ExpiresAt    sql.NullTime   `json:"expires_at"`
	ErrorMessage sql.NullString `json:"error_message"`
}

func (q *Queries) UpdateDataExportJob(ctx context.Context, arg UpdateDataExportJobParams) (DataExportJob, error) {
	row := q.db.QueryRowContext(ctx, updateDataExportJob,
		arg.ID,
		arg.Status,
		arg.FilePath,
		arg.ExpiresAt,
		arg.ErrorMessage,
	)
	var i DataExportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.FilePath,
		&i.ExpiresAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
