// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fcm.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUserFCMTokens = `-- name: GetUserFCMTokens :many
SELECT token FROM user_fcm_tokens
WHERE user_id = $1
`

func (q *Queries) GetUserFCMTokens(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserFCMTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerFCMToken = `-- name: RegisterFCMToken :one
INSERT INTO user_fcm_tokens (
    user_id,
    token,
    device_type
) VALUES (
    $1, $2, $3
) ON CONFLICT (user_id, token) DO UPDATE SET
    last_used_at = now()
RETURNING id, user_id, token, device_type, last_used_at, created_at
`

type RegisterFCMTokenParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Token      string    `json:"token"`
	DeviceType string    `json:"device_type"`
}

func (q *Queries) RegisterFCMToken(ctx context.Context, arg RegisterFCMTokenParams) (UserFcmToken, error) {
	row := q.db.QueryRowContext(ctx, registerFCMToken, arg.UserID, arg.Token, arg.DeviceType)
	var i UserFcmToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.DeviceType,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const removeAllUserFCMTokens = `-- name: RemoveAllUserFCMTokens :exec
DELETE FROM user_fcm_tokens
WHERE user_id = $1
`

func (q *Queries) RemoveAllUserFCMTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeAllUserFCMTokens, userID)
	return err
}

const removeFCMToken = `-- name: RemoveFCMToken :exec
DELETE FROM user_fcm_tokens
WHERE user_id = $1 AND token = $2
`

type RemoveFCMTokenParams struct {
	UserID uuid.UUID `json:"user_id"`
	Token  string    `json:"token"`
}

func (q *Queries) RemoveFCMToken(ctx context.Context, arg RemoveFCMTokenParams) error {
	_, err := q.db.ExecContext(ctx, removeFCMToken, arg.UserID, arg.Token)
	return err
}
