// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gamification.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const awardBadge = `-- name: AwardBadge :one
INSERT INTO user_badges (
  user_id, badge_id, earned_at
) VALUES (
  $1, $2, NOW()
) ON CONFLICT (user_id, badge_id) DO NOTHING
RETURNING id, user_id, badge_id, earned_at
`

type AwardBadgeParams struct {
	UserID  uuid.UUID `json:"user_id"`
	BadgeID string    `json:"badge_id"`
}

func (q *Queries) AwardBadge(ctx context.Context, arg AwardBadgeParams) (UserBadge, error) {
	row := q.db.QueryRowContext(ctx, awardBadge, arg.UserID, arg.BadgeID)
	var i UserBadge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BadgeID,
		&i.EarnedAt,
	)
	return i, err
}

const createBadge = `-- name: CreateBadge :one
INSERT INTO badges (
  id, name, description, icon, category, requirement
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, name, description, icon, category, requirement, created_at
`

type CreateBadgeParams struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Icon        string          `json:"icon"`
	Category    string          `json:"category"`
	Requirement json.RawMessage `json:"requirement"`
}

func (q *Queries) CreateBadge(ctx context.Context, arg CreateBadgeParams) (Badge, error) {
	row := q.db.QueryRowContext(ctx, createBadge,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Category,
		arg.Requirement,
	)
	var i Badge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Category,
		&i.Requirement,
		&i.CreatedAt,
	)
	return i, err
}

const createEngagementEvent = `-- name: CreateEngagementEvent :one
INSERT INTO engagement_events (
  user_id, event_type, event_data
) VALUES (
  $1, $2, $3
) RETURNING id, user_id, event_type, event_data, created_at
`

type CreateEngagementEventParams struct {
	UserID    uuid.UUID             `json:"user_id"`
	EventType string                `json:"event_type"`
	EventData pqtype.NullRawMessage `json:"event_data"`
}

func (q *Queries) CreateEngagementEvent(ctx context.Context, arg CreateEngagementEventParams) (EngagementEvent, error) {
	row := q.db.QueryRowContext(ctx, createEngagementEvent, arg.UserID, arg.EventType, arg.EventData)
	var i EngagementEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.EventData,
		&i.CreatedAt,
	)
	return i, err
}

const getBadge = `-- name: GetBadge :one
SELECT id, name, description, icon, category, requirement, created_at FROM badges
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBadge(ctx context.Context, id string) (Badge, error) {
	row := q.db.QueryRowContext(ctx, getBadge, id)
	var i Badge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Category,
		&i.Requirement,
		&i.CreatedAt,
	)
	return i, err
}

const getDailyStats = `-- name: GetDailyStats :many
SELECT id, user_id, date, crossings_count, stories_posted, messages_sent, locations_updated, created_at FROM daily_stats
WHERE user_id = $1 AND date >= $2
ORDER BY date DESC
`

type GetDailyStatsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Date   time.Time `json:"date"`
}

func (q *Queries) GetDailyStats(ctx context.Context, arg GetDailyStatsParams) ([]DailyStat, error) {
	rows, err := q.db.QueryContext(ctx, getDailyStats, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyStat
	for rows.Next() {
		var i DailyStat
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.CrossingsCount,
			&i.StoriesPosted,
			&i.MessagesSent,
			&i.LocationsUpdated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationPreferences = `-- name: GetNotificationPreferences :one
SELECT user_id, push_enabled, email_enabled, crossing_alerts, message_alerts, story_alerts, updated_at FROM notification_preferences
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetNotificationPreferences(ctx context.Context, userID uuid.UUID) (NotificationPreference, error) {
	row := q.db.QueryRowContext(ctx, getNotificationPreferences, userID)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.PushEnabled,
		&i.EmailEnabled,
		&i.CrossingAlerts,
		&i.MessageAlerts,
		&i.StoryAlerts,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBadges = `-- name: GetUserBadges :many
SELECT b.id, b.name, b.description, b.icon, b.category, b.requirement, b.created_at, ub.earned_at
FROM badges b
JOIN user_badges ub ON b.id = ub.badge_id
WHERE ub.user_id = $1
ORDER BY ub.earned_at DESC
`

type GetUserBadgesRow struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Icon        string          `json:"icon"`
	Category    string          `json:"category"`
	Requirement json.RawMessage `json:"requirement"`
	CreatedAt   sql.NullTime    `json:"created_at"`
	EarnedAt    sql.NullTime    `json:"earned_at"`
}

func (q *Queries) GetUserBadges(ctx context.Context, userID uuid.UUID) ([]GetUserBadgesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserBadges, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserBadgesRow
	for rows.Next() {
		var i GetUserBadgesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Category,
			&i.Requirement,
			&i.CreatedAt,
			&i.EarnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStreak = `-- name: GetUserStreak :one
SELECT user_id, current_streak, longest_streak, last_activity_date, updated_at FROM user_streaks
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserStreak(ctx context.Context, userID uuid.UUID) (UserStreak, error) {
	row := q.db.QueryRowContext(ctx, getUserStreak, userID)
	var i UserStreak
	err := row.Scan(
		&i.UserID,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityDate,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementDailyStats = `-- name: IncrementDailyStats :one
INSERT INTO daily_stats (
  user_id,
  date,
  crossings_count,
  stories_posted,
  messages_sent,
  locations_updated
) VALUES (
  $1, $2, 
  COALESCE($3, 0), 
  COALESCE($4, 0), 
  COALESCE($5, 0), 
  COALESCE($6, 0)
) ON CONFLICT (user_id, date) DO UPDATE SET
  crossings_count = daily_stats.crossings_count + COALESCE(EXCLUDED.crossings_count, 0),
  stories_posted = daily_stats.stories_posted + COALESCE(EXCLUDED.stories_posted, 0),
  messages_sent = daily_stats.messages_sent + COALESCE(EXCLUDED.messages_sent, 0),
  locations_updated = daily_stats.locations_updated + COALESCE(EXCLUDED.locations_updated, 0),
  created_at = NOW()
RETURNING id, user_id, date, crossings_count, stories_posted, messages_sent, locations_updated, created_at
`

type IncrementDailyStatsParams struct {
	UserID           uuid.UUID   `json:"user_id"`
	Date             time.Time   `json:"date"`
	CrossingsCount   interface{} `json:"crossings_count"`
	StoriesPosted    interface{} `json:"stories_posted"`
	MessagesSent     interface{} `json:"messages_sent"`
	LocationsUpdated interface{} `json:"locations_updated"`
}

func (q *Queries) IncrementDailyStats(ctx context.Context, arg IncrementDailyStatsParams) (DailyStat, error) {
	row := q.db.QueryRowContext(ctx, incrementDailyStats,
		arg.UserID,
		arg.Date,
		arg.CrossingsCount,
		arg.StoriesPosted,
		arg.MessagesSent,
		arg.LocationsUpdated,
	)
	var i DailyStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.CrossingsCount,
		&i.StoriesPosted,
		&i.MessagesSent,
		&i.LocationsUpdated,
		&i.CreatedAt,
	)
	return i, err
}

const listAllBadges = `-- name: ListAllBadges :many
SELECT id, name, description, icon, category, requirement, created_at FROM badges
ORDER BY category, name
`

func (q *Queries) ListAllBadges(ctx context.Context) ([]Badge, error) {
	rows, err := q.db.QueryContext(ctx, listAllBadges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Badge
	for rows.Next() {
		var i Badge
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Category,
			&i.Requirement,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationPreferences = `-- name: UpdateNotificationPreferences :one
INSERT INTO notification_preferences (
  user_id, push_enabled, email_enabled, crossing_alerts, message_alerts, story_alerts
) VALUES (
  $1, $2, $3, $4, $5, $6
) ON CONFLICT (user_id) DO UPDATE SET
  push_enabled = EXCLUDED.push_enabled,
  email_enabled = EXCLUDED.email_enabled,
  crossing_alerts = EXCLUDED.crossing_alerts,
  message_alerts = EXCLUDED.message_alerts,
  story_alerts = EXCLUDED.story_alerts,
  updated_at = NOW()
RETURNING user_id, push_enabled, email_enabled, crossing_alerts, message_alerts, story_alerts, updated_at
`

type UpdateNotificationPreferencesParams struct {
	UserID         uuid.UUID    `json:"user_id"`
	PushEnabled    sql.NullBool `json:"push_enabled"`
	EmailEnabled   sql.NullBool `json:"email_enabled"`
	CrossingAlerts sql.NullBool `json:"crossing_alerts"`
	MessageAlerts  sql.NullBool `json:"message_alerts"`
	StoryAlerts    sql.NullBool `json:"story_alerts"`
}

func (q *Queries) UpdateNotificationPreferences(ctx context.Context, arg UpdateNotificationPreferencesParams) (NotificationPreference, error) {
	row := q.db.QueryRowContext(ctx, updateNotificationPreferences,
		arg.UserID,
		arg.PushEnabled,
		arg.EmailEnabled,
		arg.CrossingAlerts,
		arg.MessageAlerts,
		arg.StoryAlerts,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.PushEnabled,
		&i.EmailEnabled,
		&i.CrossingAlerts,
		&i.MessageAlerts,
		&i.StoryAlerts,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStreak = `-- name: UpdateUserStreak :one
INSERT INTO user_streaks (
  user_id,
  current_streak,
  longest_streak,
  last_activity_date,
  updated_at
) VALUES (
  $1, $2, $3, $4, NOW()
) ON CONFLICT (user_id) DO UPDATE SET
  current_streak = EXCLUDED.current_streak,
  longest_streak = EXCLUDED.longest_streak,
  last_activity_date = EXCLUDED.last_activity_date,
  updated_at = NOW()
RETURNING user_id, current_streak, longest_streak, last_activity_date, updated_at
`

type UpdateUserStreakParams struct {
	UserID           uuid.UUID    `json:"user_id"`
	CurrentStreak    int32        `json:"current_streak"`
	LongestStreak    int32        `json:"longest_streak"`
	LastActivityDate sql.NullTime `json:"last_activity_date"`
}

func (q *Queries) UpdateUserStreak(ctx context.Context, arg UpdateUserStreakParams) (UserStreak, error) {
	row := q.db.QueryRowContext(ctx, updateUserStreak,
		arg.UserID,
		arg.CurrentStreak,
		arg.LongestStreak,
		arg.LastActivityDate,
	)
	var i UserStreak
	err := row.Scan(
		&i.UserID,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityDate,
		&i.UpdatedAt,
	)
	return i, err
}
