// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hashtags.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const addPostHashtag = `-- name: AddPostHashtag :exec
INSERT INTO post_hashtags (post_id, hashtag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddPostHashtagParams struct {
	PostID    uuid.UUID `json:"post_id"`
	HashtagID uuid.UUID `json:"hashtag_id"`
}

func (q *Queries) AddPostHashtag(ctx context.Context, arg AddPostHashtagParams) error {
	_, err := q.db.ExecContext(ctx, addPostHashtag, arg.PostID, arg.HashtagID)
	return err
}

const addReelHashtag = `-- name: AddReelHashtag :exec
INSERT INTO reel_hashtags (reel_id, hashtag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddReelHashtagParams struct {
	ReelID    uuid.UUID `json:"reel_id"`
	HashtagID uuid.UUID `json:"hashtag_id"`
}

func (q *Queries) AddReelHashtag(ctx context.Context, arg AddReelHashtagParams) error {
	_, err := q.db.ExecContext(ctx, addReelHashtag, arg.ReelID, arg.HashtagID)
	return err
}

const getHashtagByName = `-- name: GetHashtagByName :one
SELECT id, name, usage_count, reels_count, last_used_at, created_at, slug FROM hashtags WHERE name = $1 LIMIT 1
`

func (q *Queries) GetHashtagByName(ctx context.Context, name string) (Hashtag, error) {
	row := q.db.QueryRowContext(ctx, getHashtagByName, name)
	var i Hashtag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UsageCount,
		&i.ReelsCount,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.Slug,
	)
	return i, err
}

const getTrendingHashtags = `-- name: GetTrendingHashtags :many
SELECT id, name, usage_count, reels_count, last_used_at, created_at, slug FROM hashtags
ORDER BY 
    (usage_count + 
     (CASE WHEN last_used_at >= now() - interval '24 hours' THEN 3 ELSE 0 END) +
     (CASE WHEN last_used_at >= now() - interval '7 days' THEN 2 ELSE 0 END)) DESC,
    last_used_at DESC
LIMIT $1
`

func (q *Queries) GetTrendingHashtags(ctx context.Context, limit int32) ([]Hashtag, error) {
	rows, err := q.db.QueryContext(ctx, getTrendingHashtags, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hashtag
	for rows.Next() {
		var i Hashtag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UsageCount,
			&i.ReelsCount,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByHashtag = `-- name: ListPostsByHashtag :many
SELECT 
    p.id, p.user_id, p.media_url, p.media_type, p.caption, p.body_text, p.location_name, p.crop_settings, p.category_id,
    p.likes_count, p.comments_count, p.shares_count, p.created_at, p.updated_at,
    u.username, u.full_name, u.avatar_url,
    c.name as category_name, c.icon as category_icon,
    COALESCE((
        SELECT array_agg(h2.name)::text[] 
        FROM post_hashtags ph2 
        JOIN hashtags h2 ON ph2.hashtag_id = h2.id 
        WHERE ph2.post_id = p.id
    ), '{}')::text[] as hashtags,
    CASE WHEN p.geom IS NOT NULL THEN ST_Y(p.geom::geometry) ELSE NULL END as lat_out,
    CASE WHEN p.geom IS NOT NULL THEN ST_X(p.geom::geometry) ELSE NULL END as lng_out,
    EXISTS(SELECT 1 FROM post_likes pl WHERE pl.post_id = p.id AND pl.user_id = $1) as liked_by_viewer,
    EXISTS(SELECT 1 FROM post_saves ps WHERE ps.post_id = p.id AND ps.user_id = $1) as is_saved
FROM posts p
JOIN users u ON p.user_id = u.id
JOIN post_hashtags ph ON p.id = ph.post_id
JOIN hashtags h ON ph.hashtag_id = h.id
LEFT JOIN categories c ON p.category_id = c.id
WHERE h.name = $2
ORDER BY p.created_at DESC
LIMIT $4 OFFSET $3
`

type ListPostsByHashtagParams struct {
	ViewerID    uuid.UUID `json:"viewer_id"`
	HashtagName string    `json:"hashtag_name"`
	Off         int32     `json:"off"`
	Lim         int32     `json:"lim"`
}

type ListPostsByHashtagRow struct {
	ID            uuid.UUID             `json:"id"`
	UserID        uuid.UUID             `json:"user_id"`
	MediaUrl      string                `json:"media_url"`
	MediaType     string                `json:"media_type"`
	Caption       sql.NullString        `json:"caption"`
	BodyText      sql.NullString        `json:"body_text"`
	LocationName  sql.NullString        `json:"location_name"`
	CropSettings  pqtype.NullRawMessage `json:"crop_settings"`
	CategoryID    uuid.NullUUID         `json:"category_id"`
	LikesCount    int32                 `json:"likes_count"`
	CommentsCount int32                 `json:"comments_count"`
	SharesCount   int32                 `json:"shares_count"`
	CreatedAt     time.Time             `json:"created_at"`
	UpdatedAt     time.Time             `json:"updated_at"`
	Username      string                `json:"username"`
	FullName      string                `json:"full_name"`
	AvatarUrl     sql.NullString        `json:"avatar_url"`
	CategoryName  sql.NullString        `json:"category_name"`
	CategoryIcon  sql.NullString        `json:"category_icon"`
	Hashtags      []string              `json:"hashtags"`
	LatOut        interface{}           `json:"lat_out"`
	LngOut        interface{}           `json:"lng_out"`
	LikedByViewer bool                  `json:"liked_by_viewer"`
	IsSaved       bool                  `json:"is_saved"`
}

func (q *Queries) ListPostsByHashtag(ctx context.Context, arg ListPostsByHashtagParams) ([]ListPostsByHashtagRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsByHashtag,
		arg.ViewerID,
		arg.HashtagName,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByHashtagRow
	for rows.Next() {
		var i ListPostsByHashtagRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Caption,
			&i.BodyText,
			&i.LocationName,
			&i.CropSettings,
			&i.CategoryID,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.CategoryName,
			&i.CategoryIcon,
			pq.Array(&i.Hashtags),
			&i.LatOut,
			&i.LngOut,
			&i.LikedByViewer,
			&i.IsSaved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReelsByHashtag = `-- name: ListReelsByHashtag :many
SELECT 
    r.id, r.user_id, r.video_url, r.caption, r.is_ai_generated, r.location_name, r.geohash, r.category_id,
    COALESCE(ST_Y(r.geom::geometry)::float8, 0.0)::float8 AS lat, COALESCE(ST_X(r.geom::geometry)::float8, 0.0)::float8 AS lng,
    r.likes_count, r.comments_count, r.shares_count, r.saves_count, r.created_at, r.updated_at,
    u.username, u.avatar_url,
    EXISTS (SELECT 1 FROM reel_likes rl WHERE rl.reel_id = r.id AND rl.user_id = $3) AS is_liked,
    EXISTS (SELECT 1 FROM reel_saves rs WHERE rs.reel_id = r.id AND rs.user_id = $3) AS is_saved,
    COALESCE((SELECT status FROM connections c WHERE (c.requester_id = $3 AND c.target_id = r.user_id) OR (c.requester_id = r.user_id AND c.target_id = $3) LIMIT 1)::text, 'none') AS connection_status
FROM reels r
JOIN users u ON r.user_id = u.id
JOIN reel_hashtags rh ON r.id = rh.reel_id
JOIN hashtags h ON rh.hashtag_id = h.id
WHERE h.name = $4
ORDER BY r.created_at DESC
LIMIT $1 OFFSET $2
`

type ListReelsByHashtagParams struct {
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
	ViewerID    uuid.UUID `json:"viewer_id"`
	HashtagName string    `json:"hashtag_name"`
}

type ListReelsByHashtagRow struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	VideoUrl         string         `json:"video_url"`
	Caption          sql.NullString `json:"caption"`
	IsAiGenerated    bool           `json:"is_ai_generated"`
	LocationName     sql.NullString `json:"location_name"`
	Geohash          sql.NullString `json:"geohash"`
	CategoryID       uuid.NullUUID  `json:"category_id"`
	Lat              float64        `json:"lat"`
	Lng              float64        `json:"lng"`
	LikesCount       int32          `json:"likes_count"`
	CommentsCount    int32          `json:"comments_count"`
	SharesCount      int32          `json:"shares_count"`
	SavesCount       int32          `json:"saves_count"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	Username         string         `json:"username"`
	AvatarUrl        sql.NullString `json:"avatar_url"`
	IsLiked          bool           `json:"is_liked"`
	IsSaved          bool           `json:"is_saved"`
	ConnectionStatus interface{}    `json:"connection_status"`
}

func (q *Queries) ListReelsByHashtag(ctx context.Context, arg ListReelsByHashtagParams) ([]ListReelsByHashtagRow, error) {
	rows, err := q.db.QueryContext(ctx, listReelsByHashtag,
		arg.Limit,
		arg.Offset,
		arg.ViewerID,
		arg.HashtagName,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReelsByHashtagRow
	for rows.Next() {
		var i ListReelsByHashtagRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VideoUrl,
			&i.Caption,
			&i.IsAiGenerated,
			&i.LocationName,
			&i.Geohash,
			&i.CategoryID,
			&i.Lat,
			&i.Lng,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.SavesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AvatarUrl,
			&i.IsLiked,
			&i.IsSaved,
			&i.ConnectionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchHashtags = `-- name: SearchHashtags :many
SELECT id, name, usage_count, reels_count, last_used_at, created_at, slug FROM hashtags
WHERE name ILIKE $1 || '%'
ORDER BY usage_count DESC, last_used_at DESC
LIMIT $2
`

type SearchHashtagsParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
}

func (q *Queries) SearchHashtags(ctx context.Context, arg SearchHashtagsParams) ([]Hashtag, error) {
	rows, err := q.db.QueryContext(ctx, searchHashtags, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hashtag
	for rows.Next() {
		var i Hashtag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UsageCount,
			&i.ReelsCount,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHashtag = `-- name: UpsertHashtag :one
INSERT INTO hashtags (name, slug, usage_count, reels_count, last_used_at)
VALUES ($1, $2, 1, 1, now())
ON CONFLICT (name) DO UPDATE 
SET usage_count = hashtags.usage_count + 1,
    reels_count = hashtags.reels_count + 1,
    last_used_at = now()
RETURNING id, name, usage_count, reels_count, last_used_at, created_at, slug
`

type UpsertHashtagParams struct {
	Name string         `json:"name"`
	Slug sql.NullString `json:"slug"`
}

func (q *Queries) UpsertHashtag(ctx context.Context, arg UpsertHashtagParams) (Hashtag, error) {
	row := q.db.QueryRowContext(ctx, upsertHashtag, arg.Name, arg.Slug)
	var i Hashtag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UsageCount,
		&i.ReelsCount,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.Slug,
	)
	return i, err
}
