// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hashtags.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addPostHashtag = `-- name: AddPostHashtag :exec
INSERT INTO post_hashtags (post_id, hashtag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddPostHashtagParams struct {
	PostID    uuid.UUID `json:"post_id"`
	HashtagID uuid.UUID `json:"hashtag_id"`
}

func (q *Queries) AddPostHashtag(ctx context.Context, arg AddPostHashtagParams) error {
	_, err := q.db.ExecContext(ctx, addPostHashtag, arg.PostID, arg.HashtagID)
	return err
}

const addReelHashtag = `-- name: AddReelHashtag :exec
INSERT INTO reel_hashtags (reel_id, hashtag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddReelHashtagParams struct {
	ReelID    uuid.UUID `json:"reel_id"`
	HashtagID uuid.UUID `json:"hashtag_id"`
}

func (q *Queries) AddReelHashtag(ctx context.Context, arg AddReelHashtagParams) error {
	_, err := q.db.ExecContext(ctx, addReelHashtag, arg.ReelID, arg.HashtagID)
	return err
}

const getTrendingHashtags = `-- name: GetTrendingHashtags :many
SELECT id, name, usage_count, reels_count, last_used_at, created_at, slug FROM hashtags
ORDER BY 
    (usage_count + 
     (CASE WHEN last_used_at >= now() - interval '24 hours' THEN 3 ELSE 0 END) +
     (CASE WHEN last_used_at >= now() - interval '7 days' THEN 2 ELSE 0 END)) DESC,
    last_used_at DESC
LIMIT $1
`

func (q *Queries) GetTrendingHashtags(ctx context.Context, limit int32) ([]Hashtag, error) {
	rows, err := q.db.QueryContext(ctx, getTrendingHashtags, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hashtag
	for rows.Next() {
		var i Hashtag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UsageCount,
			&i.ReelsCount,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReelsByHashtag = `-- name: ListReelsByHashtag :many
SELECT 
    r.id, r.user_id, r.video_url, r.caption, r.is_ai_generated, r.location_name, r.geohash, r.category_id,
    COALESCE(ST_Y(r.geom::geometry)::float8, 0.0)::float8 AS lat, COALESCE(ST_X(r.geom::geometry)::float8, 0.0)::float8 AS lng,
    r.likes_count, r.comments_count, r.shares_count, r.saves_count, r.created_at, r.updated_at,
    u.username, u.avatar_url,
    EXISTS (SELECT 1 FROM reel_likes rl WHERE rl.reel_id = r.id AND rl.user_id = $3) AS is_liked,
    EXISTS (SELECT 1 FROM reel_saves rs WHERE rs.reel_id = r.id AND rs.user_id = $3) AS is_saved,
    COALESCE((SELECT status FROM connections c WHERE (c.requester_id = $3 AND c.target_id = r.user_id) OR (c.requester_id = r.user_id AND c.target_id = $3) LIMIT 1)::text, 'none') AS connection_status
FROM reels r
JOIN users u ON r.user_id = u.id
JOIN reel_hashtags rh ON r.id = rh.reel_id
JOIN hashtags h ON rh.hashtag_id = h.id
WHERE h.name = $4
ORDER BY r.created_at DESC
LIMIT $1 OFFSET $2
`

type ListReelsByHashtagParams struct {
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
	ViewerID    uuid.UUID `json:"viewer_id"`
	HashtagName string    `json:"hashtag_name"`
}

type ListReelsByHashtagRow struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	VideoUrl         string         `json:"video_url"`
	Caption          sql.NullString `json:"caption"`
	IsAiGenerated    bool           `json:"is_ai_generated"`
	LocationName     sql.NullString `json:"location_name"`
	Geohash          sql.NullString `json:"geohash"`
	CategoryID       uuid.NullUUID  `json:"category_id"`
	Lat              float64        `json:"lat"`
	Lng              float64        `json:"lng"`
	LikesCount       int32          `json:"likes_count"`
	CommentsCount    int32          `json:"comments_count"`
	SharesCount      int32          `json:"shares_count"`
	SavesCount       int32          `json:"saves_count"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	Username         string         `json:"username"`
	AvatarUrl        sql.NullString `json:"avatar_url"`
	IsLiked          bool           `json:"is_liked"`
	IsSaved          bool           `json:"is_saved"`
	ConnectionStatus interface{}    `json:"connection_status"`
}

func (q *Queries) ListReelsByHashtag(ctx context.Context, arg ListReelsByHashtagParams) ([]ListReelsByHashtagRow, error) {
	rows, err := q.db.QueryContext(ctx, listReelsByHashtag,
		arg.Limit,
		arg.Offset,
		arg.ViewerID,
		arg.HashtagName,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReelsByHashtagRow
	for rows.Next() {
		var i ListReelsByHashtagRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VideoUrl,
			&i.Caption,
			&i.IsAiGenerated,
			&i.LocationName,
			&i.Geohash,
			&i.CategoryID,
			&i.Lat,
			&i.Lng,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.SavesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AvatarUrl,
			&i.IsLiked,
			&i.IsSaved,
			&i.ConnectionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchHashtags = `-- name: SearchHashtags :many
SELECT id, name, usage_count, reels_count, last_used_at, created_at, slug FROM hashtags
WHERE name ILIKE $1 || '%'
ORDER BY usage_count DESC, last_used_at DESC
LIMIT $2
`

type SearchHashtagsParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
}

func (q *Queries) SearchHashtags(ctx context.Context, arg SearchHashtagsParams) ([]Hashtag, error) {
	rows, err := q.db.QueryContext(ctx, searchHashtags, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hashtag
	for rows.Next() {
		var i Hashtag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UsageCount,
			&i.ReelsCount,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHashtag = `-- name: UpsertHashtag :one
INSERT INTO hashtags (name, slug, usage_count, reels_count, last_used_at)
VALUES ($1, $2, 1, 1, now())
ON CONFLICT (name) DO UPDATE 
SET usage_count = hashtags.usage_count + 1,
    reels_count = hashtags.reels_count + 1,
    last_used_at = now()
RETURNING id, name, usage_count, reels_count, last_used_at, created_at, slug
`

type UpsertHashtagParams struct {
	Name string         `json:"name"`
	Slug sql.NullString `json:"slug"`
}

func (q *Queries) UpsertHashtag(ctx context.Context, arg UpsertHashtagParams) (Hashtag, error) {
	row := q.db.QueryRowContext(ctx, upsertHashtag, arg.Name, arg.Slug)
	var i Hashtag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UsageCount,
		&i.ReelsCount,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.Slug,
	)
	return i, err
}
