// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (
  user_id,
  geohash,
  geom,
  time_bucket,
  expires_at
) VALUES (
  $1, $2, ST_SetSRID(ST_MakePoint($3::float8, $4::float8), 4326), $5, $6
) RETURNING id, user_id, geohash, geom, time_bucket, created_at, expires_at
`

type CreateLocationParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Geohash    string    `json:"geohash"`
	Lng        float64   `json:"lng"`
	Lat        float64   `json:"lat"`
	TimeBucket time.Time `json:"time_bucket"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, createLocation,
		arg.UserID,
		arg.Geohash,
		arg.Lng,
		arg.Lat,
		arg.TimeBucket,
		arg.ExpiresAt,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Geohash,
		&i.Geom,
		&i.TimeBucket,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredLocations = `-- name: DeleteExpiredLocations :exec
DELETE FROM locations
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredLocations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredLocations)
	return err
}

const getHeatmapData = `-- name: GetHeatmapData :many
SELECT 
  ST_X(ST_SnapToGrid(geom, 0.001)) as longitude,
  ST_Y(ST_SnapToGrid(geom, 0.001)) as latitude,
  COUNT(*) as weight
FROM locations
WHERE time_bucket > NOW() - INTERVAL '1 hour'
GROUP BY ST_SnapToGrid(geom, 0.001)
`

type GetHeatmapDataRow struct {
	Longitude interface{} `json:"longitude"`
	Latitude  interface{} `json:"latitude"`
	Weight    int64       `json:"weight"`
}

func (q *Queries) GetHeatmapData(ctx context.Context) ([]GetHeatmapDataRow, error) {
	rows, err := q.db.QueryContext(ctx, getHeatmapData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHeatmapDataRow
	for rows.Next() {
		var i GetHeatmapDataRow
		if err := rows.Scan(&i.Longitude, &i.Latitude, &i.Weight); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNearbyUsersFromDB = `-- name: GetNearbyUsersFromDB :many
WITH recent_locations AS (
  SELECT DISTINCT ON (l.user_id)
    l.user_id,
    ST_X(l.geom) as longitude,
    ST_Y(l.geom) as latitude,
    ST_Distance(
      l.geom::geography,
      ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography
    ) / 1000.0 as distance_km
  FROM locations l
  WHERE l.expires_at > NOW()
    AND l.user_id != $3
    AND ST_DWithin(
      l.geom::geography,
      ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography,
      $4* 1000
    )
  ORDER BY l.user_id, l.time_bucket DESC
)
SELECT 
  u.id as user_id,
  u.username,
  u.full_name,
  u.avatar_url,
  u.bio,
  u.is_ghost_mode,
  u.is_shadow_banned,
  u.last_active_at,
  r.longitude,
  r.latitude,
  r.distance_km
FROM recent_locations r
JOIN users u ON r.user_id = u.id
WHERE u.is_ghost_mode = false
  AND u.is_shadow_banned = false
ORDER BY r.distance_km ASC
LIMIT 50
`

type GetNearbyUsersFromDBParams struct {
	Lng           float64     `json:"lng"`
	Lat           float64     `json:"lat"`
	ExcludeUserID uuid.UUID   `json:"exclude_user_id"`
	RadiusKm      interface{} `json:"*radius_km"`
}

type GetNearbyUsersFromDBRow struct {
	UserID         uuid.UUID      `json:"user_id"`
	Username       string         `json:"username"`
	FullName       string         `json:"full_name"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
	Bio            sql.NullString `json:"bio"`
	IsGhostMode    bool           `json:"is_ghost_mode"`
	IsShadowBanned bool           `json:"is_shadow_banned"`
	LastActiveAt   sql.NullTime   `json:"last_active_at"`
	Longitude      interface{}    `json:"longitude"`
	Latitude       interface{}    `json:"latitude"`
	DistanceKm     int32          `json:"distance_km"`
}

func (q *Queries) GetNearbyUsersFromDB(ctx context.Context, arg GetNearbyUsersFromDBParams) ([]GetNearbyUsersFromDBRow, error) {
	rows, err := q.db.QueryContext(ctx, getNearbyUsersFromDB,
		arg.Lng,
		arg.Lat,
		arg.ExcludeUserID,
		arg.RadiusKm,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNearbyUsersFromDBRow
	for rows.Next() {
		var i GetNearbyUsersFromDBRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.Bio,
			&i.IsGhostMode,
			&i.IsShadowBanned,
			&i.LastActiveAt,
			&i.Longitude,
			&i.Latitude,
			&i.DistanceKm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
