// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mentions.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countUserMentions = `-- name: CountUserMentions :one
SELECT COUNT(*) as count
FROM mentions
WHERE mentioned_user_id = $1
AND created_at > $2
`

type CountUserMentionsParams struct {
	MentionedUserID uuid.UUID `json:"mentioned_user_id"`
	CreatedAt       time.Time `json:"created_at"`
}

func (q *Queries) CountUserMentions(ctx context.Context, arg CountUserMentionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserMentions, arg.MentionedUserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMention = `-- name: CreateMention :one
INSERT INTO mentions (
    entity_type,
    entity_id,
    mentioned_user_id,
    mentioned_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4
) ON CONFLICT (entity_type, entity_id, mentioned_user_id) DO NOTHING
RETURNING id, entity_type, entity_id, mentioned_user_id, mentioned_by_user_id, created_at
`

type CreateMentionParams struct {
	EntityType        string    `json:"entity_type"`
	EntityID          uuid.UUID `json:"entity_id"`
	MentionedUserID   uuid.UUID `json:"mentioned_user_id"`
	MentionedByUserID uuid.UUID `json:"mentioned_by_user_id"`
}

func (q *Queries) CreateMention(ctx context.Context, arg CreateMentionParams) (Mention, error) {
	row := q.db.QueryRowContext(ctx, createMention,
		arg.EntityType,
		arg.EntityID,
		arg.MentionedUserID,
		arg.MentionedByUserID,
	)
	var i Mention
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.MentionedUserID,
		&i.MentionedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMentionsByEntity = `-- name: DeleteMentionsByEntity :exec
DELETE FROM mentions
WHERE entity_type = $1 AND entity_id = $2
`

type DeleteMentionsByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) DeleteMentionsByEntity(ctx context.Context, arg DeleteMentionsByEntityParams) error {
	_, err := q.db.ExecContext(ctx, deleteMentionsByEntity, arg.EntityType, arg.EntityID)
	return err
}

const getMentionedUsersByEntity = `-- name: GetMentionedUsersByEntity :many
SELECT m.id, m.entity_type, m.entity_id, m.mentioned_user_id, m.created_at,
       u.username, u.full_name, u.avatar_url
FROM mentions m
JOIN users u ON m.mentioned_user_id = u.id
WHERE m.entity_type = $1 AND m.entity_id = $2
ORDER BY m.created_at ASC
`

type GetMentionedUsersByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

type GetMentionedUsersByEntityRow struct {
	ID              uuid.UUID      `json:"id"`
	EntityType      string         `json:"entity_type"`
	EntityID        uuid.UUID      `json:"entity_id"`
	MentionedUserID uuid.UUID      `json:"mentioned_user_id"`
	CreatedAt       time.Time      `json:"created_at"`
	Username        string         `json:"username"`
	FullName        string         `json:"full_name"`
	AvatarUrl       sql.NullString `json:"avatar_url"`
}

func (q *Queries) GetMentionedUsersByEntity(ctx context.Context, arg GetMentionedUsersByEntityParams) ([]GetMentionedUsersByEntityRow, error) {
	rows, err := q.db.QueryContext(ctx, getMentionedUsersByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMentionedUsersByEntityRow
	for rows.Next() {
		var i GetMentionedUsersByEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.MentionedUserID,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserMentionsForEntity = `-- name: GetUserMentionsForEntity :many
SELECT m.id, m.entity_type, m.entity_id, m.created_at,
       u.username as mentioned_by_username
FROM mentions m
JOIN users u ON m.mentioned_by_user_id = u.id
WHERE m.mentioned_user_id = $1
ORDER BY m.created_at DESC
LIMIT $3 OFFSET $2
`

type GetUserMentionsForEntityParams struct {
	UserID uuid.UUID `json:"user_id"`
	Off    int32     `json:"off"`
	Lim    int32     `json:"lim"`
}

type GetUserMentionsForEntityRow struct {
	ID                  uuid.UUID `json:"id"`
	EntityType          string    `json:"entity_type"`
	EntityID            uuid.UUID `json:"entity_id"`
	CreatedAt           time.Time `json:"created_at"`
	MentionedByUsername string    `json:"mentioned_by_username"`
}

func (q *Queries) GetUserMentionsForEntity(ctx context.Context, arg GetUserMentionsForEntityParams) ([]GetUserMentionsForEntityRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserMentionsForEntity, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserMentionsForEntityRow
	for rows.Next() {
		var i GetUserMentionsForEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
			&i.MentionedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
