// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_settings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getNotificationSettings = `-- name: GetNotificationSettings :one
SELECT user_id, email_notifications, push_notifications, marketing_emails, activity_notifications, updated_at FROM notification_settings WHERE user_id = $1
`

func (q *Queries) GetNotificationSettings(ctx context.Context, userID uuid.UUID) (NotificationSetting, error) {
	row := q.db.QueryRowContext(ctx, getNotificationSettings, userID)
	var i NotificationSetting
	err := row.Scan(
		&i.UserID,
		&i.EmailNotifications,
		&i.PushNotifications,
		&i.MarketingEmails,
		&i.ActivityNotifications,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNotificationSettings = `-- name: UpsertNotificationSettings :one
INSERT INTO notification_settings (
    user_id, email_notifications, push_notifications, marketing_emails, activity_notifications, updated_at
) VALUES (
    $1, $2, $3, $4, $5, NOW()
) ON CONFLICT (user_id) DO UPDATE
SET 
    email_notifications = EXCLUDED.email_notifications,
    push_notifications = EXCLUDED.push_notifications,
    marketing_emails = EXCLUDED.marketing_emails,
    activity_notifications = EXCLUDED.activity_notifications,
    updated_at = NOW()
RETURNING user_id, email_notifications, push_notifications, marketing_emails, activity_notifications, updated_at
`

type UpsertNotificationSettingsParams struct {
	UserID                uuid.UUID `json:"user_id"`
	EmailNotifications    bool      `json:"email_notifications"`
	PushNotifications     bool      `json:"push_notifications"`
	MarketingEmails       bool      `json:"marketing_emails"`
	ActivityNotifications bool      `json:"activity_notifications"`
}

func (q *Queries) UpsertNotificationSettings(ctx context.Context, arg UpsertNotificationSettingsParams) (NotificationSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertNotificationSettings,
		arg.UserID,
		arg.EmailNotifications,
		arg.PushNotifications,
		arg.MarketingEmails,
		arg.ActivityNotifications,
	)
	var i NotificationSetting
	err := row.Scan(
		&i.UserID,
		&i.EmailNotifications,
		&i.PushNotifications,
		&i.MarketingEmails,
		&i.ActivityNotifications,
		&i.UpdatedAt,
	)
	return i, err
}
