// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countNotificationsAdmin = `-- name: CountNotificationsAdmin :one
SELECT COUNT(*) FROM notifications
WHERE type = 'system_announcement'
`

// Admin: Count notifications
func (q *Queries) CountNotificationsAdmin(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotificationsAdmin)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
  user_id,
  type,
  sub_type,
  sound,
  title,
  message,
  related_user_id,
  related_story_id,
  related_crossing_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, user_id, type, title, message, related_user_id, related_story_id, related_crossing_id, is_read, created_at, sub_type, sound
`

type CreateNotificationParams struct {
	UserID            uuid.UUID        `json:"user_id"`
	Type              NotificationType `json:"type"`
	SubType           sql.NullString   `json:"sub_type"`
	Sound             sql.NullString   `json:"sound"`
	Title             string           `json:"title"`
	Message           string           `json:"message"`
	RelatedUserID     uuid.NullUUID    `json:"related_user_id"`
	RelatedStoryID    uuid.NullUUID    `json:"related_story_id"`
	RelatedCrossingID uuid.NullUUID    `json:"related_crossing_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.SubType,
		arg.Sound,
		arg.Title,
		arg.Message,
		arg.RelatedUserID,
		arg.RelatedStoryID,
		arg.RelatedCrossingID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.RelatedUserID,
		&i.RelatedStoryID,
		&i.RelatedCrossingID,
		&i.IsRead,
		&i.CreatedAt,
		&i.SubType,
		&i.Sound,
	)
	return i, err
}

const deleteConnectionRequestNotifications = `-- name: DeleteConnectionRequestNotifications :exec
DELETE FROM notifications
WHERE user_id = $1 
  AND type = 'connection_request' 
  AND related_user_id = $2
`

type DeleteConnectionRequestNotificationsParams struct {
	UserID        uuid.UUID     `json:"user_id"`
	RelatedUserID uuid.NullUUID `json:"related_user_id"`
}

func (q *Queries) DeleteConnectionRequestNotifications(ctx context.Context, arg DeleteConnectionRequestNotificationsParams) error {
	_, err := q.db.ExecContext(ctx, deleteConnectionRequestNotifications, arg.UserID, arg.RelatedUserID)
	return err
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :exec
DELETE FROM notifications
WHERE created_at < NOW() - INTERVAL '30 days'
`

// Delete notifications older than 30 days
func (q *Queries) DeleteOldNotifications(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOldNotifications)
	return err
}

const listNotifications = `-- name: ListNotifications :many
SELECT 
    n.id, n.user_id, n.type, n.title, n.message, n.related_user_id, n.related_story_id, n.related_crossing_id, n.is_read, n.created_at, n.sub_type, n.sound,
    COALESCE(u.username, '')::text as actor_username,
    COALESCE(u.full_name, '')::text as actor_full_name,
    COALESCE(u.avatar_url, '')::text as actor_avatar_url
FROM notifications n
LEFT JOIN users u ON n.related_user_id = u.id
WHERE n.user_id = $1
ORDER BY n.created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListNotificationsRow struct {
	ID                uuid.UUID        `json:"id"`
	UserID            uuid.UUID        `json:"user_id"`
	Type              NotificationType `json:"type"`
	Title             string           `json:"title"`
	Message           string           `json:"message"`
	RelatedUserID     uuid.NullUUID    `json:"related_user_id"`
	RelatedStoryID    uuid.NullUUID    `json:"related_story_id"`
	RelatedCrossingID uuid.NullUUID    `json:"related_crossing_id"`
	IsRead            bool             `json:"is_read"`
	CreatedAt         time.Time        `json:"created_at"`
	SubType           sql.NullString   `json:"sub_type"`
	Sound             sql.NullString   `json:"sound"`
	ActorUsername     string           `json:"actor_username"`
	ActorFullName     string           `json:"actor_full_name"`
	ActorAvatarUrl    string           `json:"actor_avatar_url"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsRow
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.RelatedUserID,
			&i.RelatedStoryID,
			&i.RelatedCrossingID,
			&i.IsRead,
			&i.CreatedAt,
			&i.SubType,
			&i.Sound,
			&i.ActorUsername,
			&i.ActorFullName,
			&i.ActorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsAdmin = `-- name: ListNotificationsAdmin :many
SELECT 
    n.id, n.user_id, n.type, n.title, n.message, n.related_user_id, n.related_story_id, n.related_crossing_id, n.is_read, n.created_at, n.sub_type, n.sound,
    COALESCE(u.username, '')::text as actor_username,
    COALESCE(u.full_name, '')::text as actor_full_name,
    COALESCE(u.avatar_url, '')::text as actor_avatar_url
FROM notifications n
LEFT JOIN users u ON n.related_user_id = u.id
WHERE n.type = 'system_announcement'
ORDER BY n.created_at DESC
LIMIT $1 OFFSET $2
`

type ListNotificationsAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListNotificationsAdminRow struct {
	ID                uuid.UUID        `json:"id"`
	UserID            uuid.UUID        `json:"user_id"`
	Type              NotificationType `json:"type"`
	Title             string           `json:"title"`
	Message           string           `json:"message"`
	RelatedUserID     uuid.NullUUID    `json:"related_user_id"`
	RelatedStoryID    uuid.NullUUID    `json:"related_story_id"`
	RelatedCrossingID uuid.NullUUID    `json:"related_crossing_id"`
	IsRead            bool             `json:"is_read"`
	CreatedAt         time.Time        `json:"created_at"`
	SubType           sql.NullString   `json:"sub_type"`
	Sound             sql.NullString   `json:"sound"`
	ActorUsername     string           `json:"actor_username"`
	ActorFullName     string           `json:"actor_full_name"`
	ActorAvatarUrl    string           `json:"actor_avatar_url"`
}

// Admin: List all notifications (for admin panel)
func (q *Queries) ListNotificationsAdmin(ctx context.Context, arg ListNotificationsAdminParams) ([]ListNotificationsAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsAdminRow
	for rows.Next() {
		var i ListNotificationsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.RelatedUserID,
			&i.RelatedStoryID,
			&i.RelatedCrossingID,
			&i.IsRead,
			&i.CreatedAt,
			&i.SubType,
			&i.Sound,
			&i.ActorUsername,
			&i.ActorFullName,
			&i.ActorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET is_read = true
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsAsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :one
UPDATE notifications
SET is_read = true
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, type, title, message, related_user_id, related_story_id, related_crossing_id, is_read, created_at, sub_type, sound
`

type MarkNotificationAsReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.RelatedUserID,
		&i.RelatedStoryID,
		&i.RelatedCrossingID,
		&i.IsRead,
		&i.CreatedAt,
		&i.SubType,
		&i.Sound,
	)
	return i, err
}
