// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: places.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getPlace = `-- name: GetPlace :one
SELECT id, name, slug, address, geom, post_count, created_at FROM places WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlace(ctx context.Context, id uuid.UUID) (Place, error) {
	row := q.db.QueryRowContext(ctx, getPlace, id)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Address,
		&i.Geom,
		&i.PostCount,
		&i.CreatedAt,
	)
	return i, err
}

const getPlaceBySlug = `-- name: GetPlaceBySlug :one
SELECT id, name, slug, address, geom, post_count, created_at FROM places WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetPlaceBySlug(ctx context.Context, slug string) (Place, error) {
	row := q.db.QueryRowContext(ctx, getPlaceBySlug, slug)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Address,
		&i.Geom,
		&i.PostCount,
		&i.CreatedAt,
	)
	return i, err
}

const incrementPlacePostCount = `-- name: IncrementPlacePostCount :exec
UPDATE places SET post_count = post_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPlacePostCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementPlacePostCount, id)
	return err
}

const listTrendingPlaces = `-- name: ListTrendingPlaces :many
SELECT id, name, slug, address, geom, post_count, created_at FROM places
ORDER BY post_count DESC, created_at DESC
LIMIT $1 OFFSET $2
`

type ListTrendingPlacesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTrendingPlaces(ctx context.Context, arg ListTrendingPlacesParams) ([]Place, error) {
	rows, err := q.db.QueryContext(ctx, listTrendingPlaces, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Place
	for rows.Next() {
		var i Place
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Address,
			&i.Geom,
			&i.PostCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlaces = `-- name: SearchPlaces :many
SELECT id, name, slug, address, geom, post_count, created_at FROM places
WHERE name ILIKE '%' || $1::text || '%'
ORDER BY post_count DESC, name ASC
LIMIT $3 OFFSET $2
`

type SearchPlacesParams struct {
	Query string `json:"query"`
	Off   int32  `json:"off"`
	Lim   int32  `json:"lim"`
}

func (q *Queries) SearchPlaces(ctx context.Context, arg SearchPlacesParams) ([]Place, error) {
	rows, err := q.db.QueryContext(ctx, searchPlaces, arg.Query, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Place
	for rows.Next() {
		var i Place
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Address,
			&i.Geom,
			&i.PostCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlace = `-- name: UpsertPlace :one
INSERT INTO places (name, slug, address, geom)
VALUES ($1, $2, $3, 
    CASE WHEN $4::bool THEN ST_SetSRID(ST_MakePoint($5::float8, $6::float8), 4326) ELSE NULL END)
ON CONFLICT (name) DO UPDATE SET post_count = places.post_count + 1
RETURNING id, name, slug, address, geom, post_count, created_at
`

type UpsertPlaceParams struct {
	Name    string         `json:"name"`
	Slug    string         `json:"slug"`
	Address sql.NullString `json:"address"`
	Column4 bool           `json:"column_4"`
	Column5 float64        `json:"column_5"`
	Column6 float64        `json:"column_6"`
}

func (q *Queries) UpsertPlace(ctx context.Context, arg UpsertPlaceParams) (Place, error) {
	row := q.db.QueryRowContext(ctx, upsertPlace,
		arg.Name,
		arg.Slug,
		arg.Address,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Address,
		&i.Geom,
		&i.PostCount,
		&i.CreatedAt,
	)
	return i, err
}
