// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const adminDeletePost = `-- name: AdminDeletePost :exec
DELETE FROM posts WHERE id = $1
`

func (q *Queries) AdminDeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, adminDeletePost, id)
	return err
}

const adminDeletePostComment = `-- name: AdminDeletePostComment :one
DELETE FROM post_comments WHERE id = $1
RETURNING post_id
`

func (q *Queries) AdminDeletePostComment(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, adminDeletePostComment, id)
	var post_id uuid.UUID
	err := row.Scan(&post_id)
	return post_id, err
}

const countAllPostsAdmin = `-- name: CountAllPostsAdmin :one
SELECT COUNT(*) FROM posts
`

func (q *Queries) CountAllPostsAdmin(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllPostsAdmin)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPostsByUserID = `-- name: CountPostsByUserID :one
SELECT COUNT(*) FROM posts WHERE user_id = $1
`

func (q *Queries) CountPostsByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPostsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSavedPosts = `-- name: CountSavedPosts :one
SELECT COUNT(*) FROM post_saves WHERE user_id = $1
`

func (q *Queries) CountSavedPosts(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSavedPosts, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (user_id, media_url, media_type, caption, body_text, location_name, geohash, geom, crop_settings)
VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,

    CASE WHEN $8::boolean
         THEN ST_SetSRID(ST_MakePoint($9::float8, $10::float8), 4326)
         ELSE NULL END,
    $11
)
RETURNING id, user_id, media_url, media_type, caption, location_name, geohash, geom, likes_count, comments_count, created_at, updated_at, body_text, shares_count, crop_settings, saves_count,
    CASE WHEN geom IS NOT NULL THEN ST_Y(geom::geometry) ELSE NULL END as lat_out,
    CASE WHEN geom IS NOT NULL THEN ST_X(geom::geometry) ELSE NULL END as lng_out
`

type CreatePostParams struct {
	UserID       uuid.UUID             `json:"user_id"`
	MediaUrl     string                `json:"media_url"`
	MediaType    string                `json:"media_type"`
	Caption      sql.NullString        `json:"caption"`
	BodyText     sql.NullString        `json:"body_text"`
	LocationName sql.NullString        `json:"location_name"`
	Geohash      sql.NullString        `json:"geohash"`
	HasLocation  bool                  `json:"has_location"`
	Lng          float64               `json:"lng"`
	Lat          float64               `json:"lat"`
	CropSettings pqtype.NullRawMessage `json:"crop_settings"`
}

type CreatePostRow struct {
	ID            uuid.UUID             `json:"id"`
	UserID        uuid.UUID             `json:"user_id"`
	MediaUrl      string                `json:"media_url"`
	MediaType     string                `json:"media_type"`
	Caption       sql.NullString        `json:"caption"`
	LocationName  sql.NullString        `json:"location_name"`
	Geohash       sql.NullString        `json:"geohash"`
	Geom          interface{}           `json:"geom"`
	LikesCount    int32                 `json:"likes_count"`
	CommentsCount int32                 `json:"comments_count"`
	CreatedAt     time.Time             `json:"created_at"`
	UpdatedAt     time.Time             `json:"updated_at"`
	BodyText      sql.NullString        `json:"body_text"`
	SharesCount   int32                 `json:"shares_count"`
	CropSettings  pqtype.NullRawMessage `json:"crop_settings"`
	SavesCount    int32                 `json:"saves_count"`
	LatOut        interface{}           `json:"lat_out"`
	LngOut        interface{}           `json:"lng_out"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.UserID,
		arg.MediaUrl,
		arg.MediaType,
		arg.Caption,
		arg.BodyText,
		arg.LocationName,
		arg.Geohash,
		arg.HasLocation,
		arg.Lng,
		arg.Lat,
		arg.CropSettings,
	)
	var i CreatePostRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MediaUrl,
		&i.MediaType,
		&i.Caption,
		&i.LocationName,
		&i.Geohash,
		&i.Geom,
		&i.LikesCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BodyText,
		&i.SharesCount,
		&i.CropSettings,
		&i.SavesCount,
		&i.LatOut,
		&i.LngOut,
	)
	return i, err
}

const createPostComment = `-- name: CreatePostComment :one
INSERT INTO post_comments (post_id, user_id, content, is_flagged)
VALUES ($1, $2, $3, $4)
RETURNING id, post_id, user_id, content, created_at, is_flagged
`

type CreatePostCommentParams struct {
	PostID    uuid.UUID `json:"post_id"`
	UserID    uuid.UUID `json:"user_id"`
	Content   string    `json:"content"`
	IsFlagged bool      `json:"is_flagged"`
}

func (q *Queries) CreatePostComment(ctx context.Context, arg CreatePostCommentParams) (PostComment, error) {
	row := q.db.QueryRowContext(ctx, createPostComment,
		arg.PostID,
		arg.UserID,
		arg.Content,
		arg.IsFlagged,
	)
	var i PostComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.IsFlagged,
	)
	return i, err
}

const decrementPostComments = `-- name: DecrementPostComments :exec
UPDATE posts SET comments_count = GREATEST(0, comments_count - 1) WHERE id = $1
`

func (q *Queries) DecrementPostComments(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, decrementPostComments, id)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1 AND user_id = $2
`

type DeletePostParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) error {
	_, err := q.db.ExecContext(ctx, deletePost, arg.ID, arg.UserID)
	return err
}

const deletePostComment = `-- name: DeletePostComment :one
DELETE FROM post_comments WHERE id = $1 AND user_id = $2
RETURNING post_id
`

type DeletePostCommentParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePostComment(ctx context.Context, arg DeletePostCommentParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deletePostComment, arg.ID, arg.UserID)
	var post_id uuid.UUID
	err := row.Scan(&post_id)
	return post_id, err
}

const getPost = `-- name: GetPost :one
SELECT id, user_id, media_url, media_type, caption, location_name, geohash, geom, likes_count, comments_count, created_at, updated_at, body_text, shares_count, crop_settings, saves_count FROM posts WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPost(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MediaUrl,
		&i.MediaType,
		&i.Caption,
		&i.LocationName,
		&i.Geohash,
		&i.Geom,
		&i.LikesCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BodyText,
		&i.SharesCount,
		&i.CropSettings,
		&i.SavesCount,
	)
	return i, err
}

const getPostComment = `-- name: GetPostComment :one
SELECT id, post_id, user_id, content, created_at, is_flagged FROM post_comments WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPostComment(ctx context.Context, id uuid.UUID) (PostComment, error) {
	row := q.db.QueryRowContext(ctx, getPostComment, id)
	var i PostComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.IsFlagged,
	)
	return i, err
}

const incrementPostComments = `-- name: IncrementPostComments :exec
UPDATE posts SET comments_count = comments_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPostComments(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementPostComments, id)
	return err
}

const incrementPostShares = `-- name: IncrementPostShares :exec
UPDATE posts SET shares_count = shares_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPostShares(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementPostShares, id)
	return err
}

const likePostAtomic = `-- name: LikePostAtomic :one
WITH inserted AS (
    INSERT INTO post_likes (post_id, user_id)
    VALUES ($1, $2)
    ON CONFLICT (post_id, user_id) DO NOTHING
    RETURNING post_id
)
UPDATE posts p
SET likes_count = p.likes_count + 1
FROM inserted i
WHERE p.id = i.post_id
RETURNING p.likes_count
`

type LikePostAtomicParams struct {
	PostID  uuid.UUID `json:"post_id"`
	LikerID uuid.UUID `json:"liker_id"`
}

func (q *Queries) LikePostAtomic(ctx context.Context, arg LikePostAtomicParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, likePostAtomic, arg.PostID, arg.LikerID)
	var likes_count int32
	err := row.Scan(&likes_count)
	return likes_count, err
}

const listAllPostsAdmin = `-- name: ListAllPostsAdmin :many
SELECT 
    p.id, p.user_id, p.media_url, p.media_type, p.caption, p.body_text, p.location_name,
    p.likes_count, p.comments_count, p.shares_count, p.created_at, p.updated_at,
    u.username, u.avatar_url
FROM posts p
JOIN users u ON p.user_id = u.id
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllPostsAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllPostsAdminRow struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	MediaUrl      string         `json:"media_url"`
	MediaType     string         `json:"media_type"`
	Caption       sql.NullString `json:"caption"`
	BodyText      sql.NullString `json:"body_text"`
	LocationName  sql.NullString `json:"location_name"`
	LikesCount    int32          `json:"likes_count"`
	CommentsCount int32          `json:"comments_count"`
	SharesCount   int32          `json:"shares_count"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	Username      string         `json:"username"`
	AvatarUrl     sql.NullString `json:"avatar_url"`
}

func (q *Queries) ListAllPostsAdmin(ctx context.Context, arg ListAllPostsAdminParams) ([]ListAllPostsAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPostsAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllPostsAdminRow
	for rows.Next() {
		var i ListAllPostsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Caption,
			&i.BodyText,
			&i.LocationName,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectionsPosts = `-- name: ListConnectionsPosts :many
SELECT DISTINCT ON (p.id) p.id, p.user_id, p.media_url, p.media_type, p.caption, p.body_text, p.location_name, p.crop_settings,
       p.likes_count, p.comments_count, p.shares_count, p.created_at, p.updated_at,
       u.username, u.full_name, u.avatar_url,
       CASE WHEN p.geom IS NOT NULL THEN ST_Y(p.geom::geometry) ELSE NULL END as lat_out,
       CASE WHEN p.geom IS NOT NULL THEN ST_X(p.geom::geometry) ELSE NULL END as lng_out,
       EXISTS(SELECT 1 FROM post_likes pl WHERE pl.post_id = p.id AND pl.user_id = $1) as liked_by_viewer,
       EXISTS(SELECT 1 FROM post_saves ps WHERE ps.post_id = p.id AND ps.user_id = $1) as is_saved
FROM posts p
JOIN users u ON p.user_id = u.id
LEFT JOIN connections c ON
    (c.requester_id = $1 AND c.target_id = p.user_id) OR
    (c.target_id = $1 AND c.requester_id = p.user_id)
WHERE (
    p.user_id = $1 
    OR c.status = 'accepted'
    OR (u.is_private = false AND u.is_shadow_banned = false) -- Discovery: Public users
)
AND NOT EXISTS (
    SELECT 1 FROM blocked_users bu
    WHERE (bu.blocker_id = $1 AND bu.blocked_id = p.user_id)
       OR (bu.blocker_id = p.user_id AND bu.blocked_id = $1)
)
ORDER BY p.id, p.created_at DESC
LIMIT $3 OFFSET $2
`

type ListConnectionsPostsParams struct {
	ViewerID uuid.UUID `json:"viewer_id"`
	Off      int32     `json:"off"`
	Lim      int32     `json:"lim"`
}

type ListConnectionsPostsRow struct {
	ID            uuid.UUID             `json:"id"`
	UserID        uuid.UUID             `json:"user_id"`
	MediaUrl      string                `json:"media_url"`
	MediaType     string                `json:"media_type"`
	Caption       sql.NullString        `json:"caption"`
	BodyText      sql.NullString        `json:"body_text"`
	LocationName  sql.NullString        `json:"location_name"`
	CropSettings  pqtype.NullRawMessage `json:"crop_settings"`
	LikesCount    int32                 `json:"likes_count"`
	CommentsCount int32                 `json:"comments_count"`
	SharesCount   int32                 `json:"shares_count"`
	CreatedAt     time.Time             `json:"created_at"`
	UpdatedAt     time.Time             `json:"updated_at"`
	Username      string                `json:"username"`
	FullName      string                `json:"full_name"`
	AvatarUrl     sql.NullString        `json:"avatar_url"`
	LatOut        interface{}           `json:"lat_out"`
	LngOut        interface{}           `json:"lng_out"`
	LikedByViewer bool                  `json:"liked_by_viewer"`
	IsSaved       bool                  `json:"is_saved"`
}

// Get posts from connections AND own posts AND nearby discovery (public posts)
func (q *Queries) ListConnectionsPosts(ctx context.Context, arg ListConnectionsPostsParams) ([]ListConnectionsPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listConnectionsPosts, arg.ViewerID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConnectionsPostsRow
	for rows.Next() {
		var i ListConnectionsPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Caption,
			&i.BodyText,
			&i.LocationName,
			&i.CropSettings,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.LatOut,
			&i.LngOut,
			&i.LikedByViewer,
			&i.IsSaved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLikedPostsByUserID = `-- name: ListLikedPostsByUserID :many
SELECT p.id, p.user_id, p.media_url, p.media_type, p.caption, p.location_name, p.geohash, p.geom, p.likes_count, p.comments_count, p.created_at, p.updated_at, p.body_text, p.shares_count, p.crop_settings, p.saves_count FROM posts p
JOIN post_likes pl ON p.id = pl.post_id
WHERE pl.user_id = $1
ORDER BY pl.created_at DESC
`

func (q *Queries) ListLikedPostsByUserID(ctx context.Context, userID uuid.UUID) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listLikedPostsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Caption,
			&i.LocationName,
			&i.Geohash,
			&i.Geom,
			&i.LikesCount,
			&i.CommentsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BodyText,
			&i.SharesCount,
			&i.CropSettings,
			&i.SavesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostComments = `-- name: ListPostComments :many
SELECT pc.id, pc.post_id, pc.user_id, pc.content, pc.created_at,
       u.username, u.full_name, u.avatar_url
FROM post_comments pc
JOIN users u ON pc.user_id = u.id
WHERE pc.post_id = $1
ORDER BY pc.created_at ASC
LIMIT 20
`

type ListPostCommentsRow struct {
	ID        uuid.UUID      `json:"id"`
	PostID    uuid.UUID      `json:"post_id"`
	UserID    uuid.UUID      `json:"user_id"`
	Content   string         `json:"content"`
	CreatedAt time.Time      `json:"created_at"`
	Username  string         `json:"username"`
	FullName  string         `json:"full_name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) ListPostComments(ctx context.Context, postID uuid.UUID) ([]ListPostCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostComments, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostCommentsRow
	for rows.Next() {
		var i ListPostCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByUserID = `-- name: ListPostsByUserID :many
SELECT p.id, p.user_id, p.media_url, p.media_type, p.caption, p.body_text, p.location_name, p.crop_settings,
       p.likes_count, p.comments_count, p.shares_count, p.created_at, p.updated_at,

       u.username, u.full_name, u.avatar_url,
       CASE WHEN p.geom IS NOT NULL THEN ST_Y(p.geom::geometry) ELSE NULL END as lat_out,
       CASE WHEN p.geom IS NOT NULL THEN ST_X(p.geom::geometry) ELSE NULL END as lng_out,
       EXISTS(SELECT 1 FROM post_likes pl WHERE pl.post_id = p.id AND pl.user_id = $1) as liked_by_viewer,
       EXISTS(SELECT 1 FROM post_saves ps WHERE ps.post_id = p.id AND ps.user_id = $1) as is_saved
FROM posts p
JOIN users u ON p.user_id = u.id
WHERE p.user_id = $2
ORDER BY p.created_at DESC
LIMIT $4 OFFSET $3
`

type ListPostsByUserIDParams struct {
	ViewerID uuid.UUID `json:"viewer_id"`
	UserID   uuid.UUID `json:"user_id"`
	Off      int32     `json:"off"`
	Lim      int32     `json:"lim"`
}

type ListPostsByUserIDRow struct {
	ID            uuid.UUID             `json:"id"`
	UserID        uuid.UUID             `json:"user_id"`
	MediaUrl      string                `json:"media_url"`
	MediaType     string                `json:"media_type"`
	Caption       sql.NullString        `json:"caption"`
	BodyText      sql.NullString        `json:"body_text"`
	LocationName  sql.NullString        `json:"location_name"`
	CropSettings  pqtype.NullRawMessage `json:"crop_settings"`
	LikesCount    int32                 `json:"likes_count"`
	CommentsCount int32                 `json:"comments_count"`
	SharesCount   int32                 `json:"shares_count"`
	CreatedAt     time.Time             `json:"created_at"`
	UpdatedAt     time.Time             `json:"updated_at"`
	Username      string                `json:"username"`
	FullName      string                `json:"full_name"`
	AvatarUrl     sql.NullString        `json:"avatar_url"`
	LatOut        interface{}           `json:"lat_out"`
	LngOut        interface{}           `json:"lng_out"`
	LikedByViewer bool                  `json:"liked_by_viewer"`
	IsSaved       bool                  `json:"is_saved"`
}

func (q *Queries) ListPostsByUserID(ctx context.Context, arg ListPostsByUserIDParams) ([]ListPostsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsByUserID,
		arg.ViewerID,
		arg.UserID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByUserIDRow
	for rows.Next() {
		var i ListPostsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Caption,
			&i.BodyText,
			&i.LocationName,
			&i.CropSettings,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.LatOut,
			&i.LngOut,
			&i.LikedByViewer,
			&i.IsSaved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedPosts = `-- name: ListSavedPosts :many
SELECT p.id, p.user_id, p.media_url, p.media_type, p.caption, p.body_text, p.location_name, p.crop_settings,
       p.likes_count, p.comments_count, p.shares_count, p.created_at, p.updated_at,
       u.username, u.full_name, u.avatar_url,
       TRUE as is_saved,
       EXISTS(SELECT 1 FROM post_likes pl WHERE pl.post_id = p.id AND pl.user_id = $1) as liked_by_viewer
FROM posts p
JOIN users u ON p.user_id = u.id
JOIN post_saves ps ON p.id = ps.post_id
WHERE ps.user_id = $1
ORDER BY ps.created_at DESC
LIMIT $3 OFFSET $2
`

type ListSavedPostsParams struct {
	ViewerID uuid.UUID `json:"viewer_id"`
	Off      int32     `json:"off"`
	Lim      int32     `json:"lim"`
}

type ListSavedPostsRow struct {
	ID            uuid.UUID             `json:"id"`
	UserID        uuid.UUID             `json:"user_id"`
	MediaUrl      string                `json:"media_url"`
	MediaType     string                `json:"media_type"`
	Caption       sql.NullString        `json:"caption"`
	BodyText      sql.NullString        `json:"body_text"`
	LocationName  sql.NullString        `json:"location_name"`
	CropSettings  pqtype.NullRawMessage `json:"crop_settings"`
	LikesCount    int32                 `json:"likes_count"`
	CommentsCount int32                 `json:"comments_count"`
	SharesCount   int32                 `json:"shares_count"`
	CreatedAt     time.Time             `json:"created_at"`
	UpdatedAt     time.Time             `json:"updated_at"`
	Username      string                `json:"username"`
	FullName      string                `json:"full_name"`
	AvatarUrl     sql.NullString        `json:"avatar_url"`
	IsSaved       bool                  `json:"is_saved"`
	LikedByViewer bool                  `json:"liked_by_viewer"`
}

func (q *Queries) ListSavedPosts(ctx context.Context, arg ListSavedPostsParams) ([]ListSavedPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSavedPosts, arg.ViewerID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSavedPostsRow
	for rows.Next() {
		var i ListSavedPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Caption,
			&i.BodyText,
			&i.LocationName,
			&i.CropSettings,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.IsSaved,
			&i.LikedByViewer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const savePostAtomic = `-- name: SavePostAtomic :one
WITH inserted AS (
    INSERT INTO post_saves (post_id, user_id)
    VALUES ($1, $2)
    ON CONFLICT (post_id, user_id) DO NOTHING
    RETURNING post_id
)
UPDATE posts p
SET saves_count = p.saves_count + 1
FROM inserted i
WHERE p.id = i.post_id
RETURNING p.saves_count
`

type SavePostAtomicParams struct {
	PostID uuid.UUID `json:"post_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SavePostAtomic(ctx context.Context, arg SavePostAtomicParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, savePostAtomic, arg.PostID, arg.UserID)
	var saves_count int32
	err := row.Scan(&saves_count)
	return saves_count, err
}

const unlikePostAtomic = `-- name: UnlikePostAtomic :one
WITH deleted AS (
    DELETE FROM post_likes
    WHERE post_likes.post_id = $1 AND post_likes.user_id = $2
    RETURNING post_id
)
UPDATE posts p
SET likes_count = GREATEST(0, p.likes_count - 1)
FROM deleted d
WHERE p.id = d.post_id
RETURNING p.likes_count
`

type UnlikePostAtomicParams struct {
	PostID  uuid.UUID `json:"post_id"`
	LikerID uuid.UUID `json:"liker_id"`
}

func (q *Queries) UnlikePostAtomic(ctx context.Context, arg UnlikePostAtomicParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, unlikePostAtomic, arg.PostID, arg.LikerID)
	var likes_count int32
	err := row.Scan(&likes_count)
	return likes_count, err
}

const unsavePostAtomic = `-- name: UnsavePostAtomic :one
WITH deleted AS (
    DELETE FROM post_saves
    WHERE post_saves.post_id = $1 AND post_saves.user_id = $2
    RETURNING post_id
)
UPDATE posts p
SET saves_count = GREATEST(0, p.saves_count - 1)
FROM deleted d
WHERE p.id = d.post_id
RETURNING p.saves_count
`

type UnsavePostAtomicParams struct {
	PostID uuid.UUID `json:"post_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UnsavePostAtomic(ctx context.Context, arg UnsavePostAtomicParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, unsavePostAtomic, arg.PostID, arg.UserID)
	var saves_count int32
	err := row.Scan(&saves_count)
	return saves_count, err
}
