// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: preferences.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT user_id, theme, language, content_filter_enabled, updated_at FROM user_preferences WHERE user_id = $1
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID uuid.UUID) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Theme,
		&i.Language,
		&i.ContentFilterEnabled,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserPreferences = `-- name: UpsertUserPreferences :one
INSERT INTO user_preferences (
    user_id, theme, language, content_filter_enabled, updated_at
) VALUES (
    $1, $2, $3, $4, NOW()
) ON CONFLICT (user_id) DO UPDATE
SET 
    theme = EXCLUDED.theme,
    language = EXCLUDED.language,
    content_filter_enabled = EXCLUDED.content_filter_enabled,
    updated_at = NOW()
RETURNING user_id, theme, language, content_filter_enabled, updated_at
`

type UpsertUserPreferencesParams struct {
	UserID               uuid.UUID `json:"user_id"`
	Theme                string    `json:"theme"`
	Language             string    `json:"language"`
	ContentFilterEnabled bool      `json:"content_filter_enabled"`
}

func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, upsertUserPreferences,
		arg.UserID,
		arg.Theme,
		arg.Language,
		arg.ContentFilterEnabled,
	)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Theme,
		&i.Language,
		&i.ContentFilterEnabled,
		&i.UpdatedAt,
	)
	return i, err
}
