// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (GroupMember, error)
	AddReelHashtag(ctx context.Context, arg AddReelHashtagParams) error
	// Add a new reserved username (admin only)
	AddReservedUsername(ctx context.Context, arg AddReservedUsernameParams) error
	AddStoryToHighlight(ctx context.Context, arg AddStoryToHighlightParams) (HighlightStory, error)
	AdminDeletePost(ctx context.Context, id uuid.UUID) error
	AdminDeletePostComment(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	AdminDeleteReel(ctx context.Context, id uuid.UUID) error
	AdminDeleteReelComment(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	ArchiveStory(ctx context.Context, arg ArchiveStoryParams) (ArchivedStory, error)
	AwardBadge(ctx context.Context, arg AwardBadgeParams) (UserBadge, error)
	BanUser(ctx context.Context, arg BanUserParams) (User, error)
	BlockSession(ctx context.Context, userID uuid.UUID) error
	BlockUser(ctx context.Context, arg BlockUserParams) (BlockedUser, error)
	BoostUser(ctx context.Context, arg BoostUserParams) (User, error)
	CheckGroupMembership(ctx context.Context, arg CheckGroupMembershipParams) (bool, error)
	// Check if a username exists (case-insensitive)
	CheckUsernameExists(ctx context.Context, lower string) (bool, error)
	CompleteUserProfile(ctx context.Context, arg CompleteUserProfileParams) (User, error)
	CountAdminCrossings(ctx context.Context) (int64, error)
	CountAllPostsAdmin(ctx context.Context) (int64, error)
	CountAllReelsAdmin(ctx context.Context) (int64, error)
	CountArchivedStories(ctx context.Context, userID uuid.UUID) (int64, error)
	CountConnectionRequestsToday(ctx context.Context, requesterID uuid.UUID) (int64, error)
	CountCrossingsToday(ctx context.Context, userID1 uuid.UUID) (int64, error)
	// Admin: Count notifications
	CountNotificationsAdmin(ctx context.Context) (int64, error)
	CountPostsByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	CountReelsByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	CountReportsAgainstUser(ctx context.Context, targetID uuid.NullUUID) (int64, error)
	CountReportsForUser(ctx context.Context, targetUserID uuid.NullUUID) (int64, error)
	CountSavedPosts(ctx context.Context, userID uuid.UUID) (int64, error)
	CountSavedReels(ctx context.Context, userID uuid.UUID) (int64, error)
	CountSearchUsersAdmin(ctx context.Context, query string) (int64, error)
	CountStoryReactions(ctx context.Context, storyID uuid.UUID) (int64, error)
	CountStoryViews(ctx context.Context, storyID uuid.UUID) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUserMentions(ctx context.Context, arg CountUserMentionsParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error)
	CreateBadge(ctx context.Context, arg CreateBadgeParams) (Badge, error)
	CreateConnectionRequest(ctx context.Context, arg CreateConnectionRequestParams) (Connection, error)
	CreateCrossing(ctx context.Context, arg CreateCrossingParams) (Crossing, error)
	CreateDataExportJob(ctx context.Context, userID uuid.UUID) (DataExportJob, error)
	CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error)
	CreateEngagementEvent(ctx context.Context, arg CreateEngagementEventParams) (EngagementEvent, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateHighlight(ctx context.Context, arg CreateHighlightParams) (HighlightGroup, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateMention(ctx context.Context, arg CreateMentionParams) (Mention, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateMessageReaction(ctx context.Context, arg CreateMessageReactionParams) (MessageReaction, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error)
	CreatePhoneVerification(ctx context.Context, arg CreatePhoneVerificationParams) (PhoneVerification, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error)
	CreatePostComment(ctx context.Context, arg CreatePostCommentParams) (PostComment, error)
	CreateReel(ctx context.Context, arg CreateReelParams) (CreateReelRow, error)
	CreateReelComment(ctx context.Context, arg CreateReelCommentParams) (ReelComment, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateStory(ctx context.Context, arg CreateStoryParams) (CreateStoryRow, error)
	CreateStoryMention(ctx context.Context, arg CreateStoryMentionParams) (StoryMention, error)
	// Story Reactions
	CreateStoryReaction(ctx context.Context, arg CreateStoryReactionParams) (StoryReaction, error)
	// Story Views
	CreateStoryView(ctx context.Context, arg CreateStoryViewParams) (StoryView, error)
	CreateSupportTicket(ctx context.Context, arg CreateSupportTicketParams) (SupportTicket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserAuditLog(ctx context.Context, arg CreateUserAuditLogParams) (UserActivityLog, error)
	DecrementPostComments(ctx context.Context, id uuid.UUID) error
	DecrementReelComments(ctx context.Context, id uuid.UUID) error
	DeleteActivityLog(ctx context.Context, id uuid.UUID) error
	DeleteAllNotifications(ctx context.Context, userID uuid.UUID) error
	// Used for panic mode - deletes all user data
	DeleteAllUserData(ctx context.Context, id uuid.UUID) error
	DeleteArchivedStory(ctx context.Context, arg DeleteArchivedStoryParams) error
	DeleteConnection(ctx context.Context, arg DeleteConnectionParams) error
	DeleteConnectionRequestNotifications(ctx context.Context, arg DeleteConnectionRequestNotificationsParams) error
	DeleteConversation(ctx context.Context, arg DeleteConversationParams) error
	DeleteEmailVerification(ctx context.Context, userID uuid.UUID) error
	DeleteExpiredLocations(ctx context.Context) error
	DeleteExpiredMessages(ctx context.Context) error
	DeleteExpiredPasswordResets(ctx context.Context) error
	DeleteExpiredStories(ctx context.Context) error
	DeleteHighlight(ctx context.Context, arg DeleteHighlightParams) error
	DeleteMentionsByEntity(ctx context.Context, arg DeleteMentionsByEntityParams) error
	DeleteMessage(ctx context.Context, arg DeleteMessageParams) error
	DeleteMessageReaction(ctx context.Context, arg DeleteMessageReactionParams) error
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error
	// Delete messages older than specified days (default: 30 days)
	DeleteOldMessages(ctx context.Context) error
	// Delete notifications older than 30 days
	DeleteOldNotifications(ctx context.Context) error
	DeletePasswordResetByToken(ctx context.Context, token string) error
	DeletePhoneVerification(ctx context.Context, userID uuid.UUID) error
	DeletePost(ctx context.Context, arg DeletePostParams) error
	DeletePostComment(ctx context.Context, arg DeletePostCommentParams) (uuid.UUID, error)
	DeleteReel(ctx context.Context, arg DeleteReelParams) error
	DeleteReelComment(ctx context.Context, arg DeleteReelCommentParams) (uuid.UUID, error)
	// Admin: Delete story
	DeleteStory(ctx context.Context, id uuid.UUID) error
	DeleteStoryMentions(ctx context.Context, storyID uuid.UUID) error
	DeleteStoryReaction(ctx context.Context, arg DeleteStoryReactionParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserPasswordResets(ctx context.Context, userID uuid.UUID) error
	// Block Logic
	FindPotentialCrossings(ctx context.Context, arg FindPotentialCrossingsParams) ([]FindPotentialCrossingsRow, error)
	// Find usernames similar to the given pattern (for suggestions)
	// Uses trigram similarity if available, otherwise simple LIKE
	FindSimilarUsernames(ctx context.Context, pattern string) ([]string, error)
	GetActiveStoriesByUserID(ctx context.Context, userID uuid.UUID) ([]GetActiveStoriesByUserIDRow, error)
	GetArchivedStories(ctx context.Context, arg GetArchivedStoriesParams) ([]ArchivedStory, error)
	GetArchivedStory(ctx context.Context, arg GetArchivedStoryParams) (ArchivedStory, error)
	GetAuditLogsByAction(ctx context.Context, arg GetAuditLogsByActionParams) ([]UserActivityLog, error)
	GetBadge(ctx context.Context, id string) (Badge, error)
	GetBlockedUsers(ctx context.Context, blockerID uuid.UUID) ([]GetBlockedUsersRow, error)
	GetBlocksForUser(ctx context.Context, blockerID uuid.UUID) ([]GetBlocksForUserRow, error)
	GetConnection(ctx context.Context, arg GetConnectionParams) (Connection, error)
	GetConnectionSpecific(ctx context.Context, arg GetConnectionSpecificParams) (Connection, error)
	// Get stories from connected users (not limited by radius)
	GetConnectionStories(ctx context.Context, userID uuid.UUID) ([]GetConnectionStoriesRow, error)
	GetConversationList(ctx context.Context, receiverID uuid.NullUUID) ([]GetConversationListRow, error)
	GetConversionStats(ctx context.Context) (GetConversionStatsRow, error)
	GetCrossingCount(ctx context.Context, arg GetCrossingCountParams) (int64, error)
	GetCrossingsForUser(ctx context.Context, userID1 uuid.UUID) ([]Crossing, error)
	GetDailyStats(ctx context.Context, arg GetDailyStatsParams) ([]DailyStat, error)
	GetDataExportJob(ctx context.Context, id uuid.UUID) (DataExportJob, error)
	GetEmailVerification(ctx context.Context, token string) (EmailVerification, error)
	GetEmailVerificationByOTP(ctx context.Context, arg GetEmailVerificationByOTPParams) (EmailVerification, error)
	GetEngagementStats(ctx context.Context) (GetEngagementStatsRow, error)
	GetGroupByID(ctx context.Context, id uuid.UUID) (Group, error)
	GetGroupMembers(ctx context.Context, groupID uuid.UUID) ([]GetGroupMembersRow, error)
	GetGroupMessages(ctx context.Context, groupID uuid.NullUUID) ([]GetGroupMessagesRow, error)
	GetHeatmapByBounds(ctx context.Context, arg GetHeatmapByBoundsParams) ([]GetHeatmapByBoundsRow, error)
	// Returns all archived stories belonging to a highlight
	GetHighlightDetails(ctx context.Context, highlightID uuid.UUID) ([]GetHighlightDetailsRow, error)
	GetIncompleteGoogleUsers(ctx context.Context) ([]User, error)
	GetLatestCrossingBetweenUsers(ctx context.Context, arg GetLatestCrossingBetweenUsersParams) (Crossing, error)
	GetLatestDataExportJob(ctx context.Context, userID uuid.UUID) (DataExportJob, error)
	GetLatestPhoneVerification(ctx context.Context, userID uuid.UUID) (PhoneVerification, error)
	GetMentionedUsersByEntity(ctx context.Context, arg GetMentionedUsersByEntityParams) ([]GetMentionedUsersByEntityRow, error)
	GetMessage(ctx context.Context, id uuid.UUID) (Message, error)
	GetMessageReactions(ctx context.Context, messageID uuid.UUID) ([]GetMessageReactionsRow, error)
	GetMyProfileViews(ctx context.Context, viewerID uuid.UUID) ([]GetMyProfileViewsRow, error)
	GetNearbyUsersFromDB(ctx context.Context, arg GetNearbyUsersFromDBParams) ([]GetNearbyUsersFromDBRow, error)
	GetNotificationPreferences(ctx context.Context, userID uuid.UUID) (NotificationPreference, error)
	GetNotificationSettings(ctx context.Context, userID uuid.UUID) (NotificationSetting, error)
	GetPasswordResetByToken(ctx context.Context, token string) (PasswordReset, error)
	GetPost(ctx context.Context, id uuid.UUID) (Post, error)
	GetPostComment(ctx context.Context, id uuid.UUID) (PostComment, error)
	GetPrivacySettings(ctx context.Context, userID uuid.UUID) (PrivacySetting, error)
	GetProfileViewCount(ctx context.Context, viewedUserID uuid.UUID) (int64, error)
	GetRecentProfileVisitors(ctx context.Context, viewedUserID uuid.UUID) ([]GetRecentProfileVisitorsRow, error)
	GetReel(ctx context.Context, id uuid.UUID) (GetReelRow, error)
	GetReelComment(ctx context.Context, id uuid.UUID) (ReelComment, error)
	// Get all reserved usernames
	GetReservedUsernames(ctx context.Context) ([]string, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	// Get stories within a bounding box for map view
	// AND DATE(u.last_active_at) >= CURRENT_DATE - INTERVAL '1 day'
	GetStoriesInBounds(ctx context.Context, arg GetStoriesInBoundsParams) ([]GetStoriesInBoundsRow, error)
	GetStoriesWithinRadius(ctx context.Context, arg GetStoriesWithinRadiusParams) ([]GetStoriesWithinRadiusRow, error)
	GetStoryByID(ctx context.Context, id uuid.UUID) (GetStoryByIDRow, error)
	GetStoryMentions(ctx context.Context, storyID uuid.UUID) ([]GetStoryMentionsRow, error)
	GetStoryReactions(ctx context.Context, storyID uuid.UUID) ([]GetStoryReactionsRow, error)
	// Admin: Story stats
	GetStoryStats(ctx context.Context) (GetStoryStatsRow, error)
	// Only accessible by story owner
	GetStoryViewers(ctx context.Context, storyID uuid.UUID) ([]GetStoryViewersRow, error)
	GetStreakRetentionStats(ctx context.Context) (GetStreakRetentionStatsRow, error)
	GetSuggestedConnections(ctx context.Context, arg GetSuggestedConnectionsParams) ([]GetSuggestedConnectionsRow, error)
	GetSystemStats(ctx context.Context) (GetSystemStatsRow, error)
	GetTotalConnectionsCount(ctx context.Context) (int64, error)
	GetTotalCrossingsCountToday(ctx context.Context) (int64, error)
	GetTotalReelsCountToday(ctx context.Context) (int64, error)
	GetTrendingHashtags(ctx context.Context, limit int32) ([]Hashtag, error)
	GetUnreadMessageCount(ctx context.Context, receiverID uuid.NullUUID) (int64, error)
	// Get user's activity status and visibility
	GetUserActivityStatus(ctx context.Context, id uuid.UUID) (GetUserActivityStatusRow, error)
	GetUserAuditLogs(ctx context.Context, arg GetUserAuditLogsParams) ([]UserActivityLog, error)
	GetUserBadges(ctx context.Context, userID uuid.UUID) ([]GetUserBadgesRow, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID sql.NullString) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	// Find user by a previous username (for redirects/mentions)
	GetUserByPreviousUsername(ctx context.Context, lower string) (User, error)
	GetUserByUsername(ctx context.Context, lower string) (User, error)
	// Username Uniqueness System Queries
	// Get user by username (case-insensitive match)
	GetUserByUsernameCaseInsensitive(ctx context.Context, lower string) (User, error)
	GetUserEngagementStats(ctx context.Context, userID uuid.UUID) (GetUserEngagementStatsRow, error)
	GetUserFCMTokens(ctx context.Context, userID uuid.UUID) ([]string, error)
	GetUserGroups(ctx context.Context, userID uuid.UUID) ([]Group, error)
	GetUserMentions(ctx context.Context, arg GetUserMentionsParams) ([]GetUserMentionsRow, error)
	GetUserMentionsForEntity(ctx context.Context, arg GetUserMentionsForEntityParams) ([]GetUserMentionsForEntityRow, error)
	GetUserPreferences(ctx context.Context, userID uuid.UUID) (UserPreference, error)
	GetUserPrivacyState(ctx context.Context, id uuid.UUID) (GetUserPrivacyStateRow, error)
	GetUserProfile(ctx context.Context, id uuid.UUID) (GetUserProfileRow, error)
	GetUserStreak(ctx context.Context, userID uuid.UUID) (UserStreak, error)
	GetUserSupportTickets(ctx context.Context, userID uuid.UUID) ([]SupportTicket, error)
	GetUserTrustScore(ctx context.Context, id uuid.UUID) (int32, error)
	// Get username change history for a user
	GetUsernameHistory(ctx context.Context, userID uuid.UUID) ([]UsernameHistory, error)
	HasValidStory(ctx context.Context, userID uuid.UUID) (bool, error)
	IncrementDailyStats(ctx context.Context, arg IncrementDailyStatsParams) (DailyStat, error)
	IncrementPostComments(ctx context.Context, id uuid.UUID) error
	IncrementPostShares(ctx context.Context, id uuid.UUID) error
	IncrementReelComments(ctx context.Context, id uuid.UUID) error
	IncrementReelShares(ctx context.Context, id uuid.UUID) error
	IncrementReportPriority(ctx context.Context, targetID uuid.NullUUID) error
	IsUserBlocked(ctx context.Context, arg IsUserBlockedParams) (bool, error)
	// Check if a username is reserved
	IsUsernameReserved(ctx context.Context, lower string) (bool, error)
	LikePostAtomic(ctx context.Context, arg LikePostAtomicParams) (int32, error)
	LikeReelAtomic(ctx context.Context, arg LikeReelAtomicParams) (int32, error)
	ListActiveUsersWithLocation(ctx context.Context) ([]ListActiveUsersWithLocationRow, error)
	ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ListActivityLogsRow, error)
	ListAdminCrossings(ctx context.Context, arg ListAdminCrossingsParams) ([]ListAdminCrossingsRow, error)
	// Admin: List all admin/moderator users
	ListAdminUsers(ctx context.Context) ([]User, error)
	ListAllBadges(ctx context.Context) ([]Badge, error)
	ListAllBlocksAdmin(ctx context.Context, arg ListAllBlocksAdminParams) ([]ListAllBlocksAdminRow, error)
	ListAllComments(ctx context.Context, arg ListAllCommentsParams) ([]ListAllCommentsRow, error)
	ListAllPostsAdmin(ctx context.Context, arg ListAllPostsAdminParams) ([]ListAllPostsAdminRow, error)
	ListAllReelsAdmin(ctx context.Context, arg ListAllReelsAdminParams) ([]ListAllReelsAdminRow, error)
	// Admin: List all stories
	ListAllStories(ctx context.Context, arg ListAllStoriesParams) ([]ListAllStoriesRow, error)
	ListConnections(ctx context.Context, requesterID uuid.UUID) ([]ListConnectionsRow, error)
	// Get posts from connections AND own posts AND nearby discovery (public posts)
	ListConnectionsPosts(ctx context.Context, arg ListConnectionsPostsParams) ([]ListConnectionsPostsRow, error)
	ListHighlightsByUserID(ctx context.Context, userID uuid.UUID) ([]ListHighlightsByUserIDRow, error)
	ListLikedPostsByUserID(ctx context.Context, userID uuid.UUID) ([]Post, error)
	ListLikedReelsByUserID(ctx context.Context, userID uuid.UUID) ([]Reel, error)
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error)
	ListNearbyReels(ctx context.Context, arg ListNearbyReelsParams) ([]ListNearbyReelsRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error)
	// Admin: List all notifications (for admin panel)
	ListNotificationsAdmin(ctx context.Context, arg ListNotificationsAdminParams) ([]ListNotificationsAdminRow, error)
	ListPendingRequests(ctx context.Context, targetID uuid.UUID) ([]ListPendingRequestsRow, error)
	ListPostComments(ctx context.Context, postID uuid.UUID) ([]ListPostCommentsRow, error)
	ListPostsByUserID(ctx context.Context, arg ListPostsByUserIDParams) ([]ListPostsByUserIDRow, error)
	ListReelComments(ctx context.Context, reelID uuid.UUID) ([]ListReelCommentsRow, error)
	ListReelsByHashtag(ctx context.Context, arg ListReelsByHashtagParams) ([]ListReelsByHashtagRow, error)
	ListReelsFeed(ctx context.Context, arg ListReelsFeedParams) ([]ListReelsFeedRow, error)
	// Admin: List all reports
	ListReports(ctx context.Context, arg ListReportsParams) ([]ListReportsRow, error)
	ListSavedPosts(ctx context.Context, arg ListSavedPostsParams) ([]ListSavedPostsRow, error)
	ListSavedReels(ctx context.Context, arg ListSavedReelsParams) ([]ListSavedReelsRow, error)
	ListSentConnectionRequests(ctx context.Context, requesterID uuid.UUID) ([]ListSentConnectionRequestsRow, error)
	ListUserReels(ctx context.Context, arg ListUserReelsParams) ([]ListUserReelsRow, error)
	// Admin Queries
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	LogPrivacyChange(ctx context.Context, arg LogPrivacyChangeParams) (PrivacyLog, error)
	MarkAllNotificationsAsRead(ctx context.Context, userID uuid.UUID) error
	MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) error
	MarkMessageRead(ctx context.Context, arg MarkMessageReadParams) (Message, error)
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (Notification, error)
	// Record a username change in history
	RecordUsernameChange(ctx context.Context, arg RecordUsernameChangeParams) (UsernameHistory, error)
	RegisterFCMToken(ctx context.Context, arg RegisterFCMTokenParams) (UserFcmToken, error)
	RemoveAllUserFCMTokens(ctx context.Context, userID uuid.UUID) error
	RemoveFCMToken(ctx context.Context, arg RemoveFCMTokenParams) error
	RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error
	// Remove a reserved username (admin only)
	RemoveReservedUsername(ctx context.Context, lower string) error
	RemoveStoryFromHighlight(ctx context.Context, arg RemoveStoryFromHighlightParams) error
	// Admin: Resolve report
	ResolveReport(ctx context.Context, id uuid.UUID) (Report, error)
	RestoreUser(ctx context.Context, id uuid.UUID) error
	SaveMessage(ctx context.Context, id uuid.UUID) (Message, error)
	SavePostAtomic(ctx context.Context, arg SavePostAtomicParams) (int32, error)
	SaveReelAtomic(ctx context.Context, arg SaveReelAtomicParams) (int32, error)
	SearchHashtags(ctx context.Context, arg SearchHashtagsParams) ([]Hashtag, error)
	SearchUsers(ctx context.Context, query string) ([]SearchUsersRow, error)
	SearchUsersAdmin(ctx context.Context, arg SearchUsersAdminParams) ([]User, error)
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	// Privacy Features
	ToggleGhostMode(ctx context.Context, arg ToggleGhostModeParams) (User, error)
	// Privacy & Security: Panic Mode
	TogglePanicMode(ctx context.Context, arg TogglePanicModeParams) (User, error)
	TrackProfileView(ctx context.Context, arg TrackProfileViewParams) (ProfileView, error)
	UnblockUser(ctx context.Context, arg UnblockUserParams) error
	UnlikePostAtomic(ctx context.Context, arg UnlikePostAtomicParams) (int32, error)
	UnlikeReelAtomic(ctx context.Context, arg UnlikeReelAtomicParams) (int32, error)
	UnsavePostAtomic(ctx context.Context, arg UnsavePostAtomicParams) (int32, error)
	UnsaveReelAtomic(ctx context.Context, arg UnsaveReelAtomicParams) (int32, error)
	UpdateAccountPrivacy(ctx context.Context, arg UpdateAccountPrivacyParams) (User, error)
	UpdateConnectionStatus(ctx context.Context, arg UpdateConnectionStatusParams) (Connection, error)
	UpdateDataExportJob(ctx context.Context, arg UpdateDataExportJobParams) (DataExportJob, error)
	UpdateHighlightCover(ctx context.Context, arg UpdateHighlightCoverParams) (HighlightGroup, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error)
	UpdateNotificationPreferences(ctx context.Context, arg UpdateNotificationPreferencesParams) (NotificationPreference, error)
	UpdatePhoneVerificationAttempts(ctx context.Context, id uuid.UUID) (PhoneVerification, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdatePostCommentFlag(ctx context.Context, arg UpdatePostCommentFlagParams) error
	UpdateReel(ctx context.Context, arg UpdateReelParams) (Reel, error)
	UpdateReelCommentFlag(ctx context.Context, arg UpdateReelCommentFlagParams) error
	UpdateStory(ctx context.Context, arg UpdateStoryParams) (UpdateStoryRow, error)
	UpdateSupportTicketStatus(ctx context.Context, arg UpdateSupportTicketStatusParams) (SupportTicket, error)
	UpdateTwoFA(ctx context.Context, arg UpdateTwoFAParams) (User, error)
	// Updates last_active_at and calculates activity streak
	UpdateUserActivity(ctx context.Context, id uuid.UUID) (User, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (UpdateUserEmailRow, error)
	UpdateUserGoogleID(ctx context.Context, arg UpdateUserGoogleIDParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpdateUserStreak(ctx context.Context, arg UpdateUserStreakParams) (UserStreak, error)
	UpdateUserTrust(ctx context.Context, arg UpdateUserTrustParams) (User, error)
	UpdateUserTrustScore(ctx context.Context, arg UpdateUserTrustScoreParams) error
	// Update user username with history tracking
	// Note: This should be called within a transaction that also records history
	UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (User, error)
	UpsertHashtag(ctx context.Context, name string) (Hashtag, error)
	UpsertNotificationSettings(ctx context.Context, arg UpsertNotificationSettingsParams) (NotificationSetting, error)
	UpsertPrivacySettings(ctx context.Context, arg UpsertPrivacySettingsParams) (PrivacySetting, error)
	UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UserPreference, error)
	VerifyEmail(ctx context.Context, id uuid.UUID) (User, error)
	VerifyEmailWithOTP(ctx context.Context, id uuid.UUID) (User, error)
	VerifyPhone(ctx context.Context, id uuid.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
