// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reels.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const adminDeleteReel = `-- name: AdminDeleteReel :exec
DELETE FROM reels WHERE id = $1
`

func (q *Queries) AdminDeleteReel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, adminDeleteReel, id)
	return err
}

const adminDeleteReelComment = `-- name: AdminDeleteReelComment :one
DELETE FROM reel_comments WHERE id = $1
RETURNING reel_id
`

func (q *Queries) AdminDeleteReelComment(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, adminDeleteReelComment, id)
	var reel_id uuid.UUID
	err := row.Scan(&reel_id)
	return reel_id, err
}

const countAllReelsAdmin = `-- name: CountAllReelsAdmin :one
SELECT COUNT(*) FROM reels
`

func (q *Queries) CountAllReelsAdmin(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllReelsAdmin)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReelsByUserID = `-- name: CountReelsByUserID :one
SELECT COUNT(*) FROM reels WHERE user_id = $1
`

func (q *Queries) CountReelsByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReelsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSavedReels = `-- name: CountSavedReels :one
SELECT COUNT(*) FROM reel_saves WHERE user_id = $1
`

func (q *Queries) CountSavedReels(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSavedReels, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReel = `-- name: CreateReel :one
INSERT INTO reels (
    user_id, video_url, caption, is_ai_generated, location_name, geohash, geom, category_id, width, height, aspect_ratio, thumbnail_url, blur_hash, duration, file_size, mime_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id, user_id, video_url, caption, is_ai_generated, location_name, geohash, category_id,
    COALESCE(ST_Y(geom::geometry)::float8, 0.0)::float8 AS lat, COALESCE(ST_X(geom::geometry)::float8, 0.0)::float8 AS lng,
    likes_count, comments_count, shares_count, saves_count, created_at, updated_at, width, height, aspect_ratio, thumbnail_url, blur_hash, duration, file_size, mime_type
`

type CreateReelParams struct {
	UserID        uuid.UUID       `json:"user_id"`
	VideoUrl      string          `json:"video_url"`
	Caption       sql.NullString  `json:"caption"`
	IsAiGenerated bool            `json:"is_ai_generated"`
	LocationName  sql.NullString  `json:"location_name"`
	Geohash       sql.NullString  `json:"geohash"`
	Geom          interface{}     `json:"geom"`
	CategoryID    uuid.NullUUID   `json:"category_id"`
	Width         sql.NullInt32   `json:"width"`
	Height        sql.NullInt32   `json:"height"`
	AspectRatio   sql.NullFloat64 `json:"aspect_ratio"`
	ThumbnailUrl  sql.NullString  `json:"thumbnail_url"`
	BlurHash      sql.NullString  `json:"blur_hash"`
	Duration      sql.NullInt32   `json:"duration"`
	FileSize      sql.NullInt32   `json:"file_size"`
	MimeType      sql.NullString  `json:"mime_type"`
}

type CreateReelRow struct {
	ID            uuid.UUID       `json:"id"`
	UserID        uuid.UUID       `json:"user_id"`
	VideoUrl      string          `json:"video_url"`
	Caption       sql.NullString  `json:"caption"`
	IsAiGenerated bool            `json:"is_ai_generated"`
	LocationName  sql.NullString  `json:"location_name"`
	Geohash       sql.NullString  `json:"geohash"`
	CategoryID    uuid.NullUUID   `json:"category_id"`
	Lat           float64         `json:"lat"`
	Lng           float64         `json:"lng"`
	LikesCount    int32           `json:"likes_count"`
	CommentsCount int32           `json:"comments_count"`
	SharesCount   int32           `json:"shares_count"`
	SavesCount    int32           `json:"saves_count"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
	Width         sql.NullInt32   `json:"width"`
	Height        sql.NullInt32   `json:"height"`
	AspectRatio   sql.NullFloat64 `json:"aspect_ratio"`
	ThumbnailUrl  sql.NullString  `json:"thumbnail_url"`
	BlurHash      sql.NullString  `json:"blur_hash"`
	Duration      sql.NullInt32   `json:"duration"`
	FileSize      sql.NullInt32   `json:"file_size"`
	MimeType      sql.NullString  `json:"mime_type"`
}

func (q *Queries) CreateReel(ctx context.Context, arg CreateReelParams) (CreateReelRow, error) {
	row := q.db.QueryRowContext(ctx, createReel,
		arg.UserID,
		arg.VideoUrl,
		arg.Caption,
		arg.IsAiGenerated,
		arg.LocationName,
		arg.Geohash,
		arg.Geom,
		arg.CategoryID,
		arg.Width,
		arg.Height,
		arg.AspectRatio,
		arg.ThumbnailUrl,
		arg.BlurHash,
		arg.Duration,
		arg.FileSize,
		arg.MimeType,
	)
	var i CreateReelRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VideoUrl,
		&i.Caption,
		&i.IsAiGenerated,
		&i.LocationName,
		&i.Geohash,
		&i.CategoryID,
		&i.Lat,
		&i.Lng,
		&i.LikesCount,
		&i.CommentsCount,
		&i.SharesCount,
		&i.SavesCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Width,
		&i.Height,
		&i.AspectRatio,
		&i.ThumbnailUrl,
		&i.BlurHash,
		&i.Duration,
		&i.FileSize,
		&i.MimeType,
	)
	return i, err
}

const createReelComment = `-- name: CreateReelComment :one
INSERT INTO reel_comments (reel_id, user_id, content, is_flagged)
VALUES ($1, $2, $3, $4)
RETURNING id, reel_id, user_id, content, created_at, is_flagged
`

type CreateReelCommentParams struct {
	ReelID    uuid.UUID `json:"reel_id"`
	UserID    uuid.UUID `json:"user_id"`
	Content   string    `json:"content"`
	IsFlagged bool      `json:"is_flagged"`
}

func (q *Queries) CreateReelComment(ctx context.Context, arg CreateReelCommentParams) (ReelComment, error) {
	row := q.db.QueryRowContext(ctx, createReelComment,
		arg.ReelID,
		arg.UserID,
		arg.Content,
		arg.IsFlagged,
	)
	var i ReelComment
	err := row.Scan(
		&i.ID,
		&i.ReelID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.IsFlagged,
	)
	return i, err
}

const decrementReelComments = `-- name: DecrementReelComments :exec
UPDATE reels SET comments_count = GREATEST(0, comments_count - 1) WHERE id = $1
`

func (q *Queries) DecrementReelComments(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, decrementReelComments, id)
	return err
}

const deleteReel = `-- name: DeleteReel :exec
DELETE FROM reels WHERE id = $1 AND user_id = $2
`

type DeleteReelParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteReel(ctx context.Context, arg DeleteReelParams) error {
	_, err := q.db.ExecContext(ctx, deleteReel, arg.ID, arg.UserID)
	return err
}

const deleteReelComment = `-- name: DeleteReelComment :one
DELETE FROM reel_comments WHERE id = $1 AND user_id = $2
RETURNING reel_id
`

type DeleteReelCommentParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteReelComment(ctx context.Context, arg DeleteReelCommentParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteReelComment, arg.ID, arg.UserID)
	var reel_id uuid.UUID
	err := row.Scan(&reel_id)
	return reel_id, err
}

const getReel = `-- name: GetReel :one
SELECT id, user_id, video_url, caption, is_ai_generated, location_name, geohash, category_id,
    COALESCE(ST_Y(geom::geometry)::float8, 0.0)::float8 AS lat, COALESCE(ST_X(geom::geometry)::float8, 0.0)::float8 AS lng,
    likes_count, comments_count, shares_count, saves_count, created_at, updated_at, width, height, aspect_ratio, thumbnail_url, blur_hash, duration, file_size, mime_type 
FROM reels WHERE id = $1 LIMIT 1
`

type GetReelRow struct {
	ID            uuid.UUID       `json:"id"`
	UserID        uuid.UUID       `json:"user_id"`
	VideoUrl      string          `json:"video_url"`
	Caption       sql.NullString  `json:"caption"`
	IsAiGenerated bool            `json:"is_ai_generated"`
	LocationName  sql.NullString  `json:"location_name"`
	Geohash       sql.NullString  `json:"geohash"`
	CategoryID    uuid.NullUUID   `json:"category_id"`
	Lat           float64         `json:"lat"`
	Lng           float64         `json:"lng"`
	LikesCount    int32           `json:"likes_count"`
	CommentsCount int32           `json:"comments_count"`
	SharesCount   int32           `json:"shares_count"`
	SavesCount    int32           `json:"saves_count"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
	Width         sql.NullInt32   `json:"width"`
	Height        sql.NullInt32   `json:"height"`
	AspectRatio   sql.NullFloat64 `json:"aspect_ratio"`
	ThumbnailUrl  sql.NullString  `json:"thumbnail_url"`
	BlurHash      sql.NullString  `json:"blur_hash"`
	Duration      sql.NullInt32   `json:"duration"`
	FileSize      sql.NullInt32   `json:"file_size"`
	MimeType      sql.NullString  `json:"mime_type"`
}

func (q *Queries) GetReel(ctx context.Context, id uuid.UUID) (GetReelRow, error) {
	row := q.db.QueryRowContext(ctx, getReel, id)
	var i GetReelRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VideoUrl,
		&i.Caption,
		&i.IsAiGenerated,
		&i.LocationName,
		&i.Geohash,
		&i.CategoryID,
		&i.Lat,
		&i.Lng,
		&i.LikesCount,
		&i.CommentsCount,
		&i.SharesCount,
		&i.SavesCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Width,
		&i.Height,
		&i.AspectRatio,
		&i.ThumbnailUrl,
		&i.BlurHash,
		&i.Duration,
		&i.FileSize,
		&i.MimeType,
	)
	return i, err
}

const getReelComment = `-- name: GetReelComment :one
SELECT id, reel_id, user_id, content, created_at, is_flagged FROM reel_comments WHERE id = $1 LIMIT 1
`

func (q *Queries) GetReelComment(ctx context.Context, id uuid.UUID) (ReelComment, error) {
	row := q.db.QueryRowContext(ctx, getReelComment, id)
	var i ReelComment
	err := row.Scan(
		&i.ID,
		&i.ReelID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.IsFlagged,
	)
	return i, err
}

const getTotalReelsCountToday = `-- name: GetTotalReelsCountToday :one
SELECT COUNT(*) FROM reels WHERE created_at >= CURRENT_DATE
`

func (q *Queries) GetTotalReelsCountToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalReelsCountToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const incrementReelComments = `-- name: IncrementReelComments :exec
UPDATE reels SET comments_count = comments_count + 1 WHERE id = $1
`

func (q *Queries) IncrementReelComments(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementReelComments, id)
	return err
}

const incrementReelShares = `-- name: IncrementReelShares :exec
UPDATE reels SET shares_count = shares_count + 1 WHERE id = $1
`

func (q *Queries) IncrementReelShares(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementReelShares, id)
	return err
}

const likeReelAtomic = `-- name: LikeReelAtomic :one
WITH inserted AS (
    INSERT INTO reel_likes (reel_id, user_id)
    VALUES ($1, $2)
    ON CONFLICT (reel_id, user_id) DO NOTHING
    RETURNING reel_id
)
UPDATE reels r
SET likes_count = r.likes_count + 1
FROM inserted i
WHERE r.id = i.reel_id
RETURNING r.likes_count
`

type LikeReelAtomicParams struct {
	ReelID  uuid.UUID `json:"reel_id"`
	LikerID uuid.UUID `json:"liker_id"`
}

func (q *Queries) LikeReelAtomic(ctx context.Context, arg LikeReelAtomicParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, likeReelAtomic, arg.ReelID, arg.LikerID)
	var likes_count int32
	err := row.Scan(&likes_count)
	return likes_count, err
}

const listAllReelsAdmin = `-- name: ListAllReelsAdmin :many
SELECT 
    r.id, r.user_id, r.video_url, r.caption, r.is_ai_generated, r.location_name, r.geohash, r.category_id,
    r.likes_count, r.comments_count, r.shares_count, r.saves_count, r.created_at, r.updated_at, r.width, r.height, r.aspect_ratio, r.thumbnail_url, r.blur_hash, r.duration, r.file_size, r.mime_type,
    u.username, u.avatar_url
FROM reels r
JOIN users u ON r.user_id = u.id
ORDER BY r.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllReelsAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllReelsAdminRow struct {
	ID            uuid.UUID       `json:"id"`
	UserID        uuid.UUID       `json:"user_id"`
	VideoUrl      string          `json:"video_url"`
	Caption       sql.NullString  `json:"caption"`
	IsAiGenerated bool            `json:"is_ai_generated"`
	LocationName  sql.NullString  `json:"location_name"`
	Geohash       sql.NullString  `json:"geohash"`
	CategoryID    uuid.NullUUID   `json:"category_id"`
	LikesCount    int32           `json:"likes_count"`
	CommentsCount int32           `json:"comments_count"`
	SharesCount   int32           `json:"shares_count"`
	SavesCount    int32           `json:"saves_count"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
	Width         sql.NullInt32   `json:"width"`
	Height        sql.NullInt32   `json:"height"`
	AspectRatio   sql.NullFloat64 `json:"aspect_ratio"`
	ThumbnailUrl  sql.NullString  `json:"thumbnail_url"`
	BlurHash      sql.NullString  `json:"blur_hash"`
	Duration      sql.NullInt32   `json:"duration"`
	FileSize      sql.NullInt32   `json:"file_size"`
	MimeType      sql.NullString  `json:"mime_type"`
	Username      string          `json:"username"`
	AvatarUrl     sql.NullString  `json:"avatar_url"`
}

func (q *Queries) ListAllReelsAdmin(ctx context.Context, arg ListAllReelsAdminParams) ([]ListAllReelsAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllReelsAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllReelsAdminRow
	for rows.Next() {
		var i ListAllReelsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VideoUrl,
			&i.Caption,
			&i.IsAiGenerated,
			&i.LocationName,
			&i.Geohash,
			&i.CategoryID,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.SavesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Width,
			&i.Height,
			&i.AspectRatio,
			&i.ThumbnailUrl,
			&i.BlurHash,
			&i.Duration,
			&i.FileSize,
			&i.MimeType,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLikedReelsByUserID = `-- name: ListLikedReelsByUserID :many
SELECT r.id, r.user_id, r.video_url, r.caption, r.is_ai_generated, r.location_name, r.geohash, r.geom, r.likes_count, r.comments_count, r.shares_count, r.saves_count, r.created_at, r.updated_at, r.category_id, r.width, r.height, r.aspect_ratio, r.thumbnail_url, r.blur_hash, r.duration, r.file_size, r.mime_type, r.engagement_score, r.watch_time_score FROM reels r
JOIN reel_likes rl ON r.id = rl.reel_id
WHERE rl.user_id = $1
ORDER BY rl.created_at DESC
`

func (q *Queries) ListLikedReelsByUserID(ctx context.Context, userID uuid.UUID) ([]Reel, error) {
	rows, err := q.db.QueryContext(ctx, listLikedReelsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reel
	for rows.Next() {
		var i Reel
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VideoUrl,
			&i.Caption,
			&i.IsAiGenerated,
			&i.LocationName,
			&i.Geohash,
			&i.Geom,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.SavesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.Width,
			&i.Height,
			&i.AspectRatio,
			&i.ThumbnailUrl,
			&i.BlurHash,
			&i.Duration,
			&i.FileSize,
			&i.MimeType,
			&i.EngagementScore,
			&i.WatchTimeScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNearbyReels = `-- name: ListNearbyReels :many
SELECT 
    r.id, r.user_id, r.video_url, r.caption, r.is_ai_generated, r.location_name, r.geohash, r.category_id,
    COALESCE(ST_Y(r.geom::geometry)::float8, 0.0)::float8 AS lat, COALESCE(ST_X(r.geom::geometry)::float8, 0.0)::float8 AS lng,
    r.likes_count, r.comments_count, r.shares_count, r.saves_count, r.created_at, r.updated_at, r.width, r.height, r.aspect_ratio, r.thumbnail_url, r.blur_hash, r.duration, r.file_size, r.mime_type,
    u.username,
    u.avatar_url,
    ST_Distance(r.geom, ST_SetSRID(ST_MakePoint($3::float, $4::float), 4326)::geography) AS distance_meters,
    EXISTS (SELECT 1 FROM reel_likes rl WHERE rl.reel_id = r.id AND rl.user_id = $5) AS is_liked,
    EXISTS (SELECT 1 FROM reel_saves rs WHERE rs.reel_id = r.id AND rs.user_id = $5) AS is_saved,
    COALESCE((SELECT status FROM connections c WHERE (c.requester_id = $5 AND c.target_id = r.user_id) OR (c.requester_id = r.user_id AND c.target_id = $5) LIMIT 1)::text, 'none') AS connection_status
FROM reels r
JOIN users u ON r.user_id = u.id
WHERE ST_DWithin(r.geom, ST_SetSRID(ST_MakePoint($3::float, $4::float), 4326), ($6::float / 111.0) / 1000.0)
  AND ST_Distance(r.geom::geography, ST_SetSRID(ST_MakePoint($3::float, $4::float), 4326)::geography) <= $6::float
ORDER BY distance_meters ASC
LIMIT $1 OFFSET $2
`

type ListNearbyReelsParams struct {
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
	Lng      float64   `json:"lng"`
	Lat      float64   `json:"lat"`
	ViewerID uuid.UUID `json:"viewer_id"`
	Radius   float64   `json:"radius"`
}

type ListNearbyReelsRow struct {
	ID               uuid.UUID       `json:"id"`
	UserID           uuid.UUID       `json:"user_id"`
	VideoUrl         string          `json:"video_url"`
	Caption          sql.NullString  `json:"caption"`
	IsAiGenerated    bool            `json:"is_ai_generated"`
	LocationName     sql.NullString  `json:"location_name"`
	Geohash          sql.NullString  `json:"geohash"`
	CategoryID       uuid.NullUUID   `json:"category_id"`
	Lat              float64         `json:"lat"`
	Lng              float64         `json:"lng"`
	LikesCount       int32           `json:"likes_count"`
	CommentsCount    int32           `json:"comments_count"`
	SharesCount      int32           `json:"shares_count"`
	SavesCount       int32           `json:"saves_count"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	Width            sql.NullInt32   `json:"width"`
	Height           sql.NullInt32   `json:"height"`
	AspectRatio      sql.NullFloat64 `json:"aspect_ratio"`
	ThumbnailUrl     sql.NullString  `json:"thumbnail_url"`
	BlurHash         sql.NullString  `json:"blur_hash"`
	Duration         sql.NullInt32   `json:"duration"`
	FileSize         sql.NullInt32   `json:"file_size"`
	MimeType         sql.NullString  `json:"mime_type"`
	Username         string          `json:"username"`
	AvatarUrl        sql.NullString  `json:"avatar_url"`
	DistanceMeters   interface{}     `json:"distance_meters"`
	IsLiked          bool            `json:"is_liked"`
	IsSaved          bool            `json:"is_saved"`
	ConnectionStatus interface{}     `json:"connection_status"`
}

func (q *Queries) ListNearbyReels(ctx context.Context, arg ListNearbyReelsParams) ([]ListNearbyReelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNearbyReels,
		arg.Limit,
		arg.Offset,
		arg.Lng,
		arg.Lat,
		arg.ViewerID,
		arg.Radius,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNearbyReelsRow
	for rows.Next() {
		var i ListNearbyReelsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VideoUrl,
			&i.Caption,
			&i.IsAiGenerated,
			&i.LocationName,
			&i.Geohash,
			&i.CategoryID,
			&i.Lat,
			&i.Lng,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.SavesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Width,
			&i.Height,
			&i.AspectRatio,
			&i.ThumbnailUrl,
			&i.BlurHash,
			&i.Duration,
			&i.FileSize,
			&i.MimeType,
			&i.Username,
			&i.AvatarUrl,
			&i.DistanceMeters,
			&i.IsLiked,
			&i.IsSaved,
			&i.ConnectionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReelComments = `-- name: ListReelComments :many
SELECT 
    rc.id, rc.reel_id, rc.user_id, rc.content, rc.created_at, rc.is_flagged,
    u.username,
    u.avatar_url
FROM reel_comments rc
JOIN users u ON rc.user_id = u.id
WHERE rc.reel_id = $1
ORDER BY rc.created_at DESC
`

type ListReelCommentsRow struct {
	ID        uuid.UUID      `json:"id"`
	ReelID    uuid.UUID      `json:"reel_id"`
	UserID    uuid.UUID      `json:"user_id"`
	Content   string         `json:"content"`
	CreatedAt time.Time      `json:"created_at"`
	IsFlagged bool           `json:"is_flagged"`
	Username  string         `json:"username"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) ListReelComments(ctx context.Context, reelID uuid.UUID) ([]ListReelCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReelComments, reelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReelCommentsRow
	for rows.Next() {
		var i ListReelCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReelID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.IsFlagged,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReelsFeed = `-- name: ListReelsFeed :many
SELECT 
    r.id, r.user_id, r.video_url, r.caption, r.is_ai_generated, r.location_name, r.geohash, r.category_id,
    COALESCE(ST_Y(r.geom::geometry)::float8, 0.0)::float8 AS lat, COALESCE(ST_X(r.geom::geometry)::float8, 0.0)::float8 AS lng,
    r.likes_count, r.comments_count, r.shares_count, r.saves_count, r.created_at, r.updated_at, r.width, r.height, r.aspect_ratio, r.thumbnail_url, r.blur_hash, r.duration, r.file_size, r.mime_type,
    u.username,
    u.avatar_url,
    EXISTS (SELECT 1 FROM reel_likes rl WHERE rl.reel_id = r.id AND rl.user_id = $1) AS is_liked,
    EXISTS (SELECT 1 FROM reel_saves rs WHERE rs.reel_id = r.id AND rs.user_id = $1) AS is_saved,
    COALESCE((SELECT status FROM connections c WHERE (c.requester_id = $1 AND c.target_id = r.user_id) OR (c.requester_id = r.user_id AND c.target_id = $1) LIMIT 1)::text, 'none') AS connection_status
FROM reels r
JOIN users u ON r.user_id = u.id
WHERE ($2::timestamptz IS NULL OR r.created_at < $2)
ORDER BY r.created_at DESC
LIMIT $3
`

type ListReelsFeedParams struct {
	UserID uuid.UUID    `json:"user_id"`
	Cursor sql.NullTime `json:"cursor"`
	Limit  int32        `json:"limit"`
}

type ListReelsFeedRow struct {
	ID               uuid.UUID       `json:"id"`
	UserID           uuid.UUID       `json:"user_id"`
	VideoUrl         string          `json:"video_url"`
	Caption          sql.NullString  `json:"caption"`
	IsAiGenerated    bool            `json:"is_ai_generated"`
	LocationName     sql.NullString  `json:"location_name"`
	Geohash          sql.NullString  `json:"geohash"`
	CategoryID       uuid.NullUUID   `json:"category_id"`
	Lat              float64         `json:"lat"`
	Lng              float64         `json:"lng"`
	LikesCount       int32           `json:"likes_count"`
	CommentsCount    int32           `json:"comments_count"`
	SharesCount      int32           `json:"shares_count"`
	SavesCount       int32           `json:"saves_count"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	Width            sql.NullInt32   `json:"width"`
	Height           sql.NullInt32   `json:"height"`
	AspectRatio      sql.NullFloat64 `json:"aspect_ratio"`
	ThumbnailUrl     sql.NullString  `json:"thumbnail_url"`
	BlurHash         sql.NullString  `json:"blur_hash"`
	Duration         sql.NullInt32   `json:"duration"`
	FileSize         sql.NullInt32   `json:"file_size"`
	MimeType         sql.NullString  `json:"mime_type"`
	Username         string          `json:"username"`
	AvatarUrl        sql.NullString  `json:"avatar_url"`
	IsLiked          bool            `json:"is_liked"`
	IsSaved          bool            `json:"is_saved"`
	ConnectionStatus interface{}     `json:"connection_status"`
}

func (q *Queries) ListReelsFeed(ctx context.Context, arg ListReelsFeedParams) ([]ListReelsFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, listReelsFeed, arg.UserID, arg.Cursor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReelsFeedRow
	for rows.Next() {
		var i ListReelsFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VideoUrl,
			&i.Caption,
			&i.IsAiGenerated,
			&i.LocationName,
			&i.Geohash,
			&i.CategoryID,
			&i.Lat,
			&i.Lng,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.SavesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Width,
			&i.Height,
			&i.AspectRatio,
			&i.ThumbnailUrl,
			&i.BlurHash,
			&i.Duration,
			&i.FileSize,
			&i.MimeType,
			&i.Username,
			&i.AvatarUrl,
			&i.IsLiked,
			&i.IsSaved,
			&i.ConnectionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedReels = `-- name: ListSavedReels :many
SELECT 
    r.id, r.user_id, r.video_url, r.caption, r.is_ai_generated, r.location_name, r.geohash, r.category_id,
    COALESCE(ST_Y(r.geom::geometry)::float8, 0.0)::float8 AS lat, COALESCE(ST_X(r.geom::geometry)::float8, 0.0)::float8 AS lng,
    r.likes_count, r.comments_count, r.shares_count, r.saves_count, r.created_at, r.updated_at, r.width, r.height, r.aspect_ratio, r.thumbnail_url, r.blur_hash, r.duration, r.file_size, r.mime_type,
    u.username,
    u.avatar_url,
    TRUE AS is_saved,
    EXISTS (SELECT 1 FROM reel_likes rl WHERE rl.reel_id = r.id AND rl.user_id = $1) AS is_liked,
    COALESCE((SELECT status FROM connections c WHERE (c.requester_id = $1 AND c.target_id = r.user_id) OR (c.requester_id = r.user_id AND c.target_id = $1) LIMIT 1)::text, 'none') AS connection_status
FROM reels r
JOIN reel_saves rs ON r.id = rs.reel_id
JOIN users u ON r.user_id = u.id
WHERE rs.user_id = $1
ORDER BY rs.created_at DESC
LIMIT $2 OFFSET $3
`

type ListSavedReelsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListSavedReelsRow struct {
	ID               uuid.UUID       `json:"id"`
	UserID           uuid.UUID       `json:"user_id"`
	VideoUrl         string          `json:"video_url"`
	Caption          sql.NullString  `json:"caption"`
	IsAiGenerated    bool            `json:"is_ai_generated"`
	LocationName     sql.NullString  `json:"location_name"`
	Geohash          sql.NullString  `json:"geohash"`
	CategoryID       uuid.NullUUID   `json:"category_id"`
	Lat              float64         `json:"lat"`
	Lng              float64         `json:"lng"`
	LikesCount       int32           `json:"likes_count"`
	CommentsCount    int32           `json:"comments_count"`
	SharesCount      int32           `json:"shares_count"`
	SavesCount       int32           `json:"saves_count"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	Width            sql.NullInt32   `json:"width"`
	Height           sql.NullInt32   `json:"height"`
	AspectRatio      sql.NullFloat64 `json:"aspect_ratio"`
	ThumbnailUrl     sql.NullString  `json:"thumbnail_url"`
	BlurHash         sql.NullString  `json:"blur_hash"`
	Duration         sql.NullInt32   `json:"duration"`
	FileSize         sql.NullInt32   `json:"file_size"`
	MimeType         sql.NullString  `json:"mime_type"`
	Username         string          `json:"username"`
	AvatarUrl        sql.NullString  `json:"avatar_url"`
	IsSaved          bool            `json:"is_saved"`
	IsLiked          bool            `json:"is_liked"`
	ConnectionStatus interface{}     `json:"connection_status"`
}

func (q *Queries) ListSavedReels(ctx context.Context, arg ListSavedReelsParams) ([]ListSavedReelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSavedReels, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSavedReelsRow
	for rows.Next() {
		var i ListSavedReelsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VideoUrl,
			&i.Caption,
			&i.IsAiGenerated,
			&i.LocationName,
			&i.Geohash,
			&i.CategoryID,
			&i.Lat,
			&i.Lng,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.SavesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Width,
			&i.Height,
			&i.AspectRatio,
			&i.ThumbnailUrl,
			&i.BlurHash,
			&i.Duration,
			&i.FileSize,
			&i.MimeType,
			&i.Username,
			&i.AvatarUrl,
			&i.IsSaved,
			&i.IsLiked,
			&i.ConnectionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserReels = `-- name: ListUserReels :many
SELECT 
    r.id, r.user_id, r.video_url, r.caption, r.is_ai_generated, r.location_name, r.geohash, r.category_id,
    COALESCE(ST_Y(r.geom::geometry)::float8, 0.0)::float8 AS lat, COALESCE(ST_X(r.geom::geometry)::float8, 0.0)::float8 AS lng,
    r.likes_count, r.comments_count, r.shares_count, r.saves_count, r.created_at, r.updated_at, r.width, r.height, r.aspect_ratio, r.thumbnail_url, r.blur_hash, r.duration, r.file_size, r.mime_type,
    u.username,
    u.avatar_url,
    EXISTS (SELECT 1 FROM reel_likes rl WHERE rl.reel_id = r.id AND rl.user_id = $3) AS is_liked,
    EXISTS (SELECT 1 FROM reel_saves rs WHERE rs.reel_id = r.id AND rs.user_id = $3) AS is_saved,
    COALESCE((SELECT status FROM connections c WHERE (c.requester_id = $3 AND c.target_id = r.user_id) OR (c.requester_id = r.user_id AND c.target_id = $3) LIMIT 1)::text, 'none') AS connection_status
FROM reels r
JOIN users u ON r.user_id = u.id
WHERE r.user_id = $4
ORDER BY r.created_at DESC
LIMIT $1 OFFSET $2
`

type ListUserReelsParams struct {
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
	ViewerID uuid.UUID `json:"viewer_id"`
	UserID   uuid.UUID `json:"user_id"`
}

type ListUserReelsRow struct {
	ID               uuid.UUID       `json:"id"`
	UserID           uuid.UUID       `json:"user_id"`
	VideoUrl         string          `json:"video_url"`
	Caption          sql.NullString  `json:"caption"`
	IsAiGenerated    bool            `json:"is_ai_generated"`
	LocationName     sql.NullString  `json:"location_name"`
	Geohash          sql.NullString  `json:"geohash"`
	CategoryID       uuid.NullUUID   `json:"category_id"`
	Lat              float64         `json:"lat"`
	Lng              float64         `json:"lng"`
	LikesCount       int32           `json:"likes_count"`
	CommentsCount    int32           `json:"comments_count"`
	SharesCount      int32           `json:"shares_count"`
	SavesCount       int32           `json:"saves_count"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	Width            sql.NullInt32   `json:"width"`
	Height           sql.NullInt32   `json:"height"`
	AspectRatio      sql.NullFloat64 `json:"aspect_ratio"`
	ThumbnailUrl     sql.NullString  `json:"thumbnail_url"`
	BlurHash         sql.NullString  `json:"blur_hash"`
	Duration         sql.NullInt32   `json:"duration"`
	FileSize         sql.NullInt32   `json:"file_size"`
	MimeType         sql.NullString  `json:"mime_type"`
	Username         string          `json:"username"`
	AvatarUrl        sql.NullString  `json:"avatar_url"`
	IsLiked          bool            `json:"is_liked"`
	IsSaved          bool            `json:"is_saved"`
	ConnectionStatus interface{}     `json:"connection_status"`
}

func (q *Queries) ListUserReels(ctx context.Context, arg ListUserReelsParams) ([]ListUserReelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserReels,
		arg.Limit,
		arg.Offset,
		arg.ViewerID,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserReelsRow
	for rows.Next() {
		var i ListUserReelsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VideoUrl,
			&i.Caption,
			&i.IsAiGenerated,
			&i.LocationName,
			&i.Geohash,
			&i.CategoryID,
			&i.Lat,
			&i.Lng,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.SavesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Width,
			&i.Height,
			&i.AspectRatio,
			&i.ThumbnailUrl,
			&i.BlurHash,
			&i.Duration,
			&i.FileSize,
			&i.MimeType,
			&i.Username,
			&i.AvatarUrl,
			&i.IsLiked,
			&i.IsSaved,
			&i.ConnectionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveReelAtomic = `-- name: SaveReelAtomic :one
WITH inserted AS (
    INSERT INTO reel_saves (reel_id, user_id)
    VALUES ($1, $2)
    ON CONFLICT (reel_id, user_id) DO NOTHING
    RETURNING reel_id
)
UPDATE reels r
SET saves_count = r.saves_count + 1
FROM inserted i
WHERE r.id = i.reel_id
RETURNING r.saves_count
`

type SaveReelAtomicParams struct {
	ReelID  uuid.UUID `json:"reel_id"`
	SaverID uuid.UUID `json:"saver_id"`
}

func (q *Queries) SaveReelAtomic(ctx context.Context, arg SaveReelAtomicParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, saveReelAtomic, arg.ReelID, arg.SaverID)
	var saves_count int32
	err := row.Scan(&saves_count)
	return saves_count, err
}

const searchReels = `-- name: SearchReels :many
SELECT r.id, r.user_id, r.video_url, r.caption, r.is_ai_generated, r.location_name, r.geohash, r.category_id,
       COALESCE(ST_Y(r.geom::geometry)::float8, 0.0)::float8 AS lat, COALESCE(ST_X(r.geom::geometry)::float8, 0.0)::float8 AS lng,
       r.likes_count, r.comments_count, r.shares_count, r.saves_count, r.created_at, r.updated_at, r.width, r.height, r.aspect_ratio, r.thumbnail_url, r.blur_hash, r.duration, r.file_size, r.mime_type,
       u.username, u.avatar_url,
       EXISTS (SELECT 1 FROM reel_likes rl WHERE rl.reel_id = r.id AND rl.user_id = $3) AS is_liked,
       EXISTS (SELECT 1 FROM reel_saves rs WHERE rs.reel_id = r.id AND rs.user_id = $3) AS is_saved,
       COALESCE((SELECT status FROM connections c WHERE (c.requester_id = $3 AND c.target_id = r.user_id) OR (c.requester_id = r.user_id AND c.target_id = $3) LIMIT 1)::text, 'none') AS connection_status
FROM reels r
JOIN users u ON r.user_id = u.id
WHERE (r.caption ILIKE '%' || $4::text || '%'
    OR r.location_name ILIKE '%' || $4::text || '%')
  AND u.is_shadow_banned = false
ORDER BY r.likes_count DESC, r.created_at DESC
LIMIT $1 OFFSET $2
`

type SearchReelsParams struct {
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
	ViewerID uuid.UUID `json:"viewer_id"`
	Query    string    `json:"query"`
}

type SearchReelsRow struct {
	ID               uuid.UUID       `json:"id"`
	UserID           uuid.UUID       `json:"user_id"`
	VideoUrl         string          `json:"video_url"`
	Caption          sql.NullString  `json:"caption"`
	IsAiGenerated    bool            `json:"is_ai_generated"`
	LocationName     sql.NullString  `json:"location_name"`
	Geohash          sql.NullString  `json:"geohash"`
	CategoryID       uuid.NullUUID   `json:"category_id"`
	Lat              float64         `json:"lat"`
	Lng              float64         `json:"lng"`
	LikesCount       int32           `json:"likes_count"`
	CommentsCount    int32           `json:"comments_count"`
	SharesCount      int32           `json:"shares_count"`
	SavesCount       int32           `json:"saves_count"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	Width            sql.NullInt32   `json:"width"`
	Height           sql.NullInt32   `json:"height"`
	AspectRatio      sql.NullFloat64 `json:"aspect_ratio"`
	ThumbnailUrl     sql.NullString  `json:"thumbnail_url"`
	BlurHash         sql.NullString  `json:"blur_hash"`
	Duration         sql.NullInt32   `json:"duration"`
	FileSize         sql.NullInt32   `json:"file_size"`
	MimeType         sql.NullString  `json:"mime_type"`
	Username         string          `json:"username"`
	AvatarUrl        sql.NullString  `json:"avatar_url"`
	IsLiked          bool            `json:"is_liked"`
	IsSaved          bool            `json:"is_saved"`
	ConnectionStatus interface{}     `json:"connection_status"`
}

func (q *Queries) SearchReels(ctx context.Context, arg SearchReelsParams) ([]SearchReelsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchReels,
		arg.Limit,
		arg.Offset,
		arg.ViewerID,
		arg.Query,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchReelsRow
	for rows.Next() {
		var i SearchReelsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VideoUrl,
			&i.Caption,
			&i.IsAiGenerated,
			&i.LocationName,
			&i.Geohash,
			&i.CategoryID,
			&i.Lat,
			&i.Lng,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.SavesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Width,
			&i.Height,
			&i.AspectRatio,
			&i.ThumbnailUrl,
			&i.BlurHash,
			&i.Duration,
			&i.FileSize,
			&i.MimeType,
			&i.Username,
			&i.AvatarUrl,
			&i.IsLiked,
			&i.IsSaved,
			&i.ConnectionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlikeReelAtomic = `-- name: UnlikeReelAtomic :one
WITH deleted AS (
    DELETE FROM reel_likes 
    WHERE reel_likes.reel_id = $1 AND reel_likes.user_id = $2
    RETURNING reel_id
)
UPDATE reels r
SET likes_count = GREATEST(0, r.likes_count - 1)
FROM deleted d
WHERE r.id = d.reel_id
RETURNING r.likes_count
`

type UnlikeReelAtomicParams struct {
	ReelID  uuid.UUID `json:"reel_id"`
	LikerID uuid.UUID `json:"liker_id"`
}

func (q *Queries) UnlikeReelAtomic(ctx context.Context, arg UnlikeReelAtomicParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, unlikeReelAtomic, arg.ReelID, arg.LikerID)
	var likes_count int32
	err := row.Scan(&likes_count)
	return likes_count, err
}

const unsaveReelAtomic = `-- name: UnsaveReelAtomic :one
WITH deleted AS (
    DELETE FROM reel_saves
    WHERE reel_saves.reel_id = $1 AND reel_saves.user_id = $2
    RETURNING reel_id
)
UPDATE reels r
SET saves_count = GREATEST(0, r.saves_count - 1)
FROM deleted d
WHERE r.id = d.reel_id
RETURNING r.saves_count
`

type UnsaveReelAtomicParams struct {
	ReelID  uuid.UUID `json:"reel_id"`
	SaverID uuid.UUID `json:"saver_id"`
}

func (q *Queries) UnsaveReelAtomic(ctx context.Context, arg UnsaveReelAtomicParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, unsaveReelAtomic, arg.ReelID, arg.SaverID)
	var saves_count int32
	err := row.Scan(&saves_count)
	return saves_count, err
}

const updateReel = `-- name: UpdateReel :one
UPDATE reels SET caption = $1, updated_at = now() WHERE id = $2 AND user_id = $3 RETURNING id, user_id, video_url, caption, is_ai_generated, location_name, geohash, geom, likes_count, comments_count, shares_count, saves_count, created_at, updated_at, category_id, width, height, aspect_ratio, thumbnail_url, blur_hash, duration, file_size, mime_type, engagement_score, watch_time_score
`

type UpdateReelParams struct {
	Caption sql.NullString `json:"caption"`
	ID      uuid.UUID      `json:"id"`
	UserID  uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateReel(ctx context.Context, arg UpdateReelParams) (Reel, error) {
	row := q.db.QueryRowContext(ctx, updateReel, arg.Caption, arg.ID, arg.UserID)
	var i Reel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VideoUrl,
		&i.Caption,
		&i.IsAiGenerated,
		&i.LocationName,
		&i.Geohash,
		&i.Geom,
		&i.LikesCount,
		&i.CommentsCount,
		&i.SharesCount,
		&i.SavesCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.Width,
		&i.Height,
		&i.AspectRatio,
		&i.ThumbnailUrl,
		&i.BlurHash,
		&i.Duration,
		&i.FileSize,
		&i.MimeType,
		&i.EngagementScore,
		&i.WatchTimeScore,
	)
	return i, err
}
