// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relationships.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countFollowers = `-- name: CountFollowers :one
SELECT COUNT(*) FROM relationships
WHERE target_user_id = $1 AND type = 'follow' AND status = 'active'
`

func (q *Queries) CountFollowers(ctx context.Context, targetUserID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFollowers, targetUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFollowing = `-- name: CountFollowing :one
SELECT COUNT(*) FROM relationships
WHERE user_id = $1 AND type = 'follow' AND status = 'active'
`

func (q *Queries) CountFollowing(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFollowing, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRelationship = `-- name: CreateRelationship :one
INSERT INTO relationships (
    user_id,
    target_user_id,
    type,
    status
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (user_id, target_user_id, type) DO UPDATE 
SET status = EXCLUDED.status, created_at = NOW()
RETURNING id, user_id, target_user_id, type, status, created_at
`

type CreateRelationshipParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	TargetUserID uuid.UUID          `json:"target_user_id"`
	Type         RelationshipType   `json:"type"`
	Status       RelationshipStatus `json:"status"`
}

func (q *Queries) CreateRelationship(ctx context.Context, arg CreateRelationshipParams) (Relationship, error) {
	row := q.db.QueryRowContext(ctx, createRelationship,
		arg.UserID,
		arg.TargetUserID,
		arg.Type,
		arg.Status,
	)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetUserID,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRelationship = `-- name: DeleteRelationship :exec
DELETE FROM relationships
WHERE user_id = $1 AND target_user_id = $2 AND type = $3
`

type DeleteRelationshipParams struct {
	UserID       uuid.UUID        `json:"user_id"`
	TargetUserID uuid.UUID        `json:"target_user_id"`
	Type         RelationshipType `json:"type"`
}

func (q *Queries) DeleteRelationship(ctx context.Context, arg DeleteRelationshipParams) error {
	_, err := q.db.ExecContext(ctx, deleteRelationship, arg.UserID, arg.TargetUserID, arg.Type)
	return err
}

const getRelationship = `-- name: GetRelationship :one
SELECT id, user_id, target_user_id, type, status, created_at FROM relationships
WHERE user_id = $1 AND target_user_id = $2 AND type = $3
LIMIT 1
`

type GetRelationshipParams struct {
	UserID       uuid.UUID        `json:"user_id"`
	TargetUserID uuid.UUID        `json:"target_user_id"`
	Type         RelationshipType `json:"type"`
}

func (q *Queries) GetRelationship(ctx context.Context, arg GetRelationshipParams) (Relationship, error) {
	row := q.db.QueryRowContext(ctx, getRelationship, arg.UserID, arg.TargetUserID, arg.Type)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetUserID,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listFollowers = `-- name: ListFollowers :many
SELECT u.id, u.username, u.full_name, u.avatar_url, r.created_at
FROM relationships r
JOIN users u ON u.id = r.user_id
WHERE r.target_user_id = $1 AND r.type = 'follow' AND r.status = 'active'
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFollowersParams struct {
	TargetUserID uuid.UUID `json:"target_user_id"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

type ListFollowersRow struct {
	ID        uuid.UUID      `json:"id"`
	Username  string         `json:"username"`
	FullName  string         `json:"full_name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	CreatedAt time.Time      `json:"created_at"`
}

func (q *Queries) ListFollowers(ctx context.Context, arg ListFollowersParams) ([]ListFollowersRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowers, arg.TargetUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowersRow
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT u.id, u.username, u.full_name, u.avatar_url, r.created_at
FROM relationships r
JOIN users u ON u.id = r.target_user_id
WHERE r.user_id = $1 AND r.type = 'follow' AND r.status = 'active'
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFollowingParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListFollowingRow struct {
	ID        uuid.UUID      `json:"id"`
	Username  string         `json:"username"`
	FullName  string         `json:"full_name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	CreatedAt time.Time      `json:"created_at"`
}

func (q *Queries) ListFollowing(ctx context.Context, arg ListFollowingParams) ([]ListFollowingRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowing, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowingRow
	for rows.Next() {
		var i ListFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingFollowRequests = `-- name: ListPendingFollowRequests :many
SELECT 
    r.user_id as requester_id, 
    r.target_user_id as target_id, 
    r.status, 
    r.created_at,
    u.username,
    u.full_name,
    u.avatar_url
FROM relationships r
JOIN users u ON r.user_id = u.id
WHERE r.target_user_id = $1 
  AND r.type = 'follow'
  AND r.status = 'pending'
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListPendingFollowRequestsParams struct {
	TargetUserID uuid.UUID `json:"target_user_id"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

type ListPendingFollowRequestsRow struct {
	RequesterID uuid.UUID          `json:"requester_id"`
	TargetID    uuid.UUID          `json:"target_id"`
	Status      RelationshipStatus `json:"status"`
	CreatedAt   time.Time          `json:"created_at"`
	Username    string             `json:"username"`
	FullName    string             `json:"full_name"`
	AvatarUrl   sql.NullString     `json:"avatar_url"`
}

func (q *Queries) ListPendingFollowRequests(ctx context.Context, arg ListPendingFollowRequestsParams) ([]ListPendingFollowRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingFollowRequests, arg.TargetUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingFollowRequestsRow
	for rows.Next() {
		var i ListPendingFollowRequestsRow
		if err := rows.Scan(
			&i.RequesterID,
			&i.TargetID,
			&i.Status,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentFollowRequests = `-- name: ListSentFollowRequests :many
SELECT 
    r.user_id as requester_id, 
    r.target_user_id as target_id, 
    r.status, 
    r.created_at,
    u.username,
    u.full_name,
    u.avatar_url
FROM relationships r
JOIN users u ON r.target_user_id = u.id
WHERE r.user_id = $1 
  AND r.type = 'follow'
  AND r.status = 'pending'
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListSentFollowRequestsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListSentFollowRequestsRow struct {
	RequesterID uuid.UUID          `json:"requester_id"`
	TargetID    uuid.UUID          `json:"target_id"`
	Status      RelationshipStatus `json:"status"`
	CreatedAt   time.Time          `json:"created_at"`
	Username    string             `json:"username"`
	FullName    string             `json:"full_name"`
	AvatarUrl   sql.NullString     `json:"avatar_url"`
}

func (q *Queries) ListSentFollowRequests(ctx context.Context, arg ListSentFollowRequestsParams) ([]ListSentFollowRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSentFollowRequests, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSentFollowRequestsRow
	for rows.Next() {
		var i ListSentFollowRequestsRow
		if err := rows.Scan(
			&i.RequesterID,
			&i.TargetID,
			&i.Status,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRelationshipStatus = `-- name: UpdateRelationshipStatus :one
UPDATE relationships
SET status = $3
WHERE user_id = $1 AND target_user_id = $2 AND type = 'follow'
RETURNING id, user_id, target_user_id, type, status, created_at
`

type UpdateRelationshipStatusParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	TargetUserID uuid.UUID          `json:"target_user_id"`
	Status       RelationshipStatus `json:"status"`
}

func (q *Queries) UpdateRelationshipStatus(ctx context.Context, arg UpdateRelationshipStatusParams) (Relationship, error) {
	row := q.db.QueryRowContext(ctx, updateRelationshipStatus, arg.UserID, arg.TargetUserID, arg.Status)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetUserID,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
