// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: support.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSupportTicket = `-- name: CreateSupportTicket :one
INSERT INTO support_tickets (
    user_id, subject, description, priority
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, subject, description, status, priority, created_at, updated_at
`

type CreateSupportTicketParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Subject     string    `json:"subject"`
	Description string    `json:"description"`
	Priority    string    `json:"priority"`
}

func (q *Queries) CreateSupportTicket(ctx context.Context, arg CreateSupportTicketParams) (SupportTicket, error) {
	row := q.db.QueryRowContext(ctx, createSupportTicket,
		arg.UserID,
		arg.Subject,
		arg.Description,
		arg.Priority,
	)
	var i SupportTicket
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subject,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSupportTickets = `-- name: GetUserSupportTickets :many
SELECT id, user_id, subject, description, status, priority, created_at, updated_at FROM support_tickets
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUserSupportTickets(ctx context.Context, userID uuid.UUID) ([]SupportTicket, error) {
	rows, err := q.db.QueryContext(ctx, getUserSupportTickets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupportTicket
	for rows.Next() {
		var i SupportTicket
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Subject,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSupportTicketStatus = `-- name: UpdateSupportTicketStatus :one
UPDATE support_tickets
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, subject, description, status, priority, created_at, updated_at
`

type UpdateSupportTicketStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateSupportTicketStatus(ctx context.Context, arg UpdateSupportTicketStatusParams) (SupportTicket, error) {
	row := q.db.QueryRowContext(ctx, updateSupportTicketStatus, arg.ID, arg.Status)
	var i SupportTicket
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subject,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
