// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createEmailVerification = `-- name: CreateEmailVerification :one
INSERT INTO email_verifications (
    user_id,
    email,
    token,
    expires_at
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, email, token, expires_at, created_at
`

type CreateEmailVerificationParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Email     string    `json:"email"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error) {
	row := q.db.QueryRowContext(ctx, createEmailVerification,
		arg.UserID,
		arg.Email,
		arg.Token,
		arg.ExpiresAt,
	)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPhoneVerification = `-- name: CreatePhoneVerification :one
INSERT INTO phone_verifications (
    user_id,
    phone,
    code,
    expires_at
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, phone, code, expires_at, created_at, attempts
`

type CreatePhoneVerificationParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Phone     string    `json:"phone"`
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePhoneVerification(ctx context.Context, arg CreatePhoneVerificationParams) (PhoneVerification, error) {
	row := q.db.QueryRowContext(ctx, createPhoneVerification,
		arg.UserID,
		arg.Phone,
		arg.Code,
		arg.ExpiresAt,
	)
	var i PhoneVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Phone,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Attempts,
	)
	return i, err
}

const deleteEmailVerification = `-- name: DeleteEmailVerification :exec
DELETE FROM email_verifications
WHERE user_id = $1
`

func (q *Queries) DeleteEmailVerification(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEmailVerification, userID)
	return err
}

const deletePhoneVerification = `-- name: DeletePhoneVerification :exec
DELETE FROM phone_verifications
WHERE user_id = $1
`

func (q *Queries) DeletePhoneVerification(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePhoneVerification, userID)
	return err
}

const getEmailVerification = `-- name: GetEmailVerification :one
SELECT id, user_id, email, token, expires_at, created_at FROM email_verifications
WHERE token = $1 LIMIT 1
`

func (q *Queries) GetEmailVerification(ctx context.Context, token string) (EmailVerification, error) {
	row := q.db.QueryRowContext(ctx, getEmailVerification, token)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestPhoneVerification = `-- name: GetLatestPhoneVerification :one
SELECT id, user_id, phone, code, expires_at, created_at, attempts FROM phone_verifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestPhoneVerification(ctx context.Context, userID uuid.UUID) (PhoneVerification, error) {
	row := q.db.QueryRowContext(ctx, getLatestPhoneVerification, userID)
	var i PhoneVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Phone,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Attempts,
	)
	return i, err
}

const updatePhoneVerificationAttempts = `-- name: UpdatePhoneVerificationAttempts :one
UPDATE phone_verifications
SET attempts = attempts + 1
WHERE id = $1
RETURNING id, user_id, phone, code, expires_at, created_at, attempts
`

func (q *Queries) UpdatePhoneVerificationAttempts(ctx context.Context, id uuid.UUID) (PhoneVerification, error) {
	row := q.db.QueryRowContext(ctx, updatePhoneVerificationAttempts, id)
	var i PhoneVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Phone,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Attempts,
	)
	return i, err
}

const verifyEmail = `-- name: VerifyEmail :one
UPDATE users
SET is_email_verified = true,
    is_active = CASE WHEN is_phone_verified = true THEN true ELSE is_active END
WHERE id = $1
RETURNING id, phone, password_hash, username, full_name, avatar_url, bio, role, trust_level, is_verified, is_shadow_banned, last_active_at, created_at, is_ghost_mode, activity_streak, streak_updated_at, is_premium, streak_freezes_remaining, boost_expires_at, banner_url, theme, profile_visibility, email, website_url, links, google_id, provider, is_profile_complete, ghost_mode_expires_at, interests, trust_score, username_normalized, is_private, privacy_updated_at, panic_mode, deleted_at, two_fa_enabled, two_fa_secret, last_password_change, is_email_verified, is_phone_verified, is_active
`

func (q *Queries) VerifyEmail(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, verifyEmail, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.TrustLevel,
		&i.IsVerified,
		&i.IsShadowBanned,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.IsGhostMode,
		&i.ActivityStreak,
		&i.StreakUpdatedAt,
		&i.IsPremium,
		&i.StreakFreezesRemaining,
		&i.BoostExpiresAt,
		&i.BannerUrl,
		&i.Theme,
		&i.ProfileVisibility,
		&i.Email,
		&i.WebsiteUrl,
		&i.Links,
		&i.GoogleID,
		&i.Provider,
		&i.IsProfileComplete,
		&i.GhostModeExpiresAt,
		pq.Array(&i.Interests),
		&i.TrustScore,
		&i.UsernameNormalized,
		&i.IsPrivate,
		&i.PrivacyUpdatedAt,
		&i.PanicMode,
		&i.DeletedAt,
		&i.TwoFaEnabled,
		&i.TwoFaSecret,
		&i.LastPasswordChange,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.IsActive,
	)
	return i, err
}

const verifyPhone = `-- name: VerifyPhone :one
UPDATE users
SET is_phone_verified = true,
    is_active = CASE WHEN is_email_verified = true THEN true ELSE is_active END
WHERE id = $1
RETURNING id, phone, password_hash, username, full_name, avatar_url, bio, role, trust_level, is_verified, is_shadow_banned, last_active_at, created_at, is_ghost_mode, activity_streak, streak_updated_at, is_premium, streak_freezes_remaining, boost_expires_at, banner_url, theme, profile_visibility, email, website_url, links, google_id, provider, is_profile_complete, ghost_mode_expires_at, interests, trust_score, username_normalized, is_private, privacy_updated_at, panic_mode, deleted_at, two_fa_enabled, two_fa_secret, last_password_change, is_email_verified, is_phone_verified, is_active
`

func (q *Queries) VerifyPhone(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, verifyPhone, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.TrustLevel,
		&i.IsVerified,
		&i.IsShadowBanned,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.IsGhostMode,
		&i.ActivityStreak,
		&i.StreakUpdatedAt,
		&i.IsPremium,
		&i.StreakFreezesRemaining,
		&i.BoostExpiresAt,
		&i.BannerUrl,
		&i.Theme,
		&i.ProfileVisibility,
		&i.Email,
		&i.WebsiteUrl,
		&i.Links,
		&i.GoogleID,
		&i.Provider,
		&i.IsProfileComplete,
		&i.GhostModeExpiresAt,
		pq.Array(&i.Interests),
		&i.TrustScore,
		&i.UsernameNormalized,
		&i.IsPrivate,
		&i.PrivacyUpdatedAt,
		&i.PanicMode,
		&i.DeletedAt,
		&i.TwoFaEnabled,
		&i.TwoFaSecret,
		&i.LastPasswordChange,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.IsActive,
	)
	return i, err
}
