package util

import (
	"strings"
)

// disposableEmailDomains is a blocklist of known disposable/temporary email providers.
// Users signing up with these domains are rejected to prevent fake accounts.
var disposableEmailDomains = map[string]struct{}{
	// Temporary email services
	"tempmail.com":      {},
	"temp-mail.org":     {},
	"guerrillamail.com": {},
	"guerrillamail.net": {},
	"guerrillamail.org": {},
	"grr.la":            {},
	"guerrillamail.de":  {},
	"guerrillamail.biz": {},
	"sharklasers.com":   {},

	// 10minutemail style
	"10minutemail.com": {},
	"10minutemail.net": {},
	"10minutemail.org": {},
	"10minutemail.de":  {},
	"10mail.org":       {},
	"10mail.com":       {},
	"tempail.com":      {},
	"dispostable.com":  {},

	// YOPmail and variants
	"yopmail.com":     {},
	"yopmail.fr":      {},
	"yopmail.net":     {},
	"yopmail.org":     {},
	"mailnesia.com":   {},
	"mailinator.com":  {},
	"mailinator.org":  {},
	"mailinator2.com": {},
	"safe-mail.net":   {},

	// Throwaway services
	"throwaway.email": {},
	"throwaway.com":   {},
	"trashmail.com":   {},
	"trashmail.net":   {},
	"trashmail.org":   {},
	"trashmail.de":    {},
	"trashmail.me":    {},
	"trashmail.ws":    {},
	"trashmail.io":    {},

	// Fakeinbox
	"fakeinbox.com":   {},
	"fakeinbox.net":   {},
	"fakemail.net":    {},
	"fakemailz.com":   {},
	"maildrop.cc":     {},
	"maildrop.com":    {},
	"mailcatch.com":   {},
	"mailnull.com":    {},
	"spamgourmet.com": {},
	"spamgourmet.net": {},
	"spamgourmet.org": {},

	// Other popular disposable providers
	"mohmal.com":                {},
	"mohmal.net":                {},
	"burnermail.io":             {},
	"burntmail.com":             {},
	"getnada.com":               {},
	"getairmail.com":            {},
	"harakirimail.com":          {},
	"mytemp.email":              {},
	"mytempemail.com":           {},
	"tempinbox.com":             {},
	"tempr.email":               {},
	"discard.email":             {},
	"discardmail.com":           {},
	"discardmail.de":            {},
	"disposableemail.com":       {},
	"e4ward.com":                {},
	"emailondeck.com":           {},
	"filzmail.com":              {},
	"get10minutemail.com":       {},
	"getonemail.com":            {},
	"getonemail.net":            {},
	"guerrillamailblock.com":    {},
	"hostcalls.com":             {},
	"incognitomail.com":         {},
	"incognitomail.net":         {},
	"incognitomail.org":         {},
	"inboxalias.com":            {},
	"inboxkitten.com":           {},
	"letthemeatspam.com":        {},
	"mailzilla.com":             {},
	"mailzilla.org":             {},
	"mintemail.com":             {},
	"moakt.com":                 {},
	"moakt.ws":                  {},
	"moakt.co":                  {},
	"mohmal.org":                {},
	"mohmal.in":                 {},
	"mspamblocker.com":          {},
	"no-spam.ws":                {},
	"nomail.pw":                 {},
	"nomail2.me":                {},
	"nospam.ze.tc":              {},
	"nospam4.us":                {},
	"nospammail.net":            {},
	"nowmymail.com":             {},
	"objectmail.com":            {},
	"obobodo.com":               {},
	"odaymail.com":              {},
	"pookmail.com":              {},
	"spam4.me":                  {},
	"spamavert.com":             {},
	"spamfree24.com":            {},
	"spamfree24.de":             {},
	"spamfree24.eu":             {},
	"spamfree24.net":            {},
	"spamfree24.org":            {},
	"spamhole.com":              {},
	"spaml.com":                 {},
	"spamspot.com":              {},
	"spamtroll.net":             {},
	"tagyourself.com":           {},
	"tempinbox.xyz":             {},
	"tempmail.de":               {},
	"tempmaildemo.com":          {},
	"tempmailer.com":            {},
	"tempmailer.de":             {},
	"tempmailo.com":             {},
	"tempomail.fr":              {},
	"temporarily.de":            {},
	"temporaryemail.net":        {},
	"temporaryforwarding.com":   {},
	"temporaryinbox.com":        {},
	"temporarymailaddress.com":  {},
	"thanksnospam.info":         {},
	"thankyou2010.com":          {},
	"thc.st":                    {},
	"tilien.com":                {},
	"tmail.ws":                  {},
	"tradermail.info":           {},
	"trash-mail.at":             {},
	"trash-mail.com":            {},
	"trash-mail.de":             {},
	"trash-mail.net":            {},
	"trash2010.com":             {},
	"trash2011.com":             {},
	"trashdevil.com":            {},
	"trashdevil.de":             {},
	"trashymail.com":            {},
	"trashymail.net":            {},
	"trillianpro.com":           {},
	"tryalert.com":              {},
	"uggsrock.com":              {},
	"wegwerfmail.de":            {},
	"wegwerfmail.net":           {},
	"wegwerfmail.org":           {},
	"wegwerfmailadresse.com":    {},
	"wetrainbayarea.com":        {},
	"wh4f.org":                  {},
	"whyspam.me":                {},
	"willselfdestruct.com":      {},
	"winemaven.info":            {},
	"wronghead.com":             {},
	"wronghead.net":             {},
	"www.e4ward.com":            {},
	"www.mailinator.com":        {},
	"wwwnew.eu":                 {},
	"x.ip6.li":                  {},
	"xagloo.co":                 {},
	"xagloo.com":                {},
	"xcode.ro":                  {},
	"xmail.com":                 {},
	"xoxox.cc":                  {},
	"yapped.net":                {},
	"yeah.net":                  {},
	"ye.vc":                     {},
	"yogamaven.com":             {},
	"youmailr.com":              {},
	"ypmail.webarnak.fr.eu.org": {},
	"yuurok.com":                {},
	"za.com":                    {},
	"zehnminuten.de":            {},
	"zehnminutenmail.de":        {},
	"zoaxe.com":                 {},
	"zoemail.com":               {},
	"zoemail.net":               {},
	"zoemail.org":               {},
	"zipcatfish.com":            {},
	"zippymail.info":            {},
	"zomg.info":                 {},
}

// IsDisposableEmail checks if the email domain is a known disposable/temporary provider.
func IsDisposableEmail(email string) bool {
	atIdx := strings.LastIndex(email, "@")
	if atIdx == -1 || atIdx >= len(email)-1 {
		return false
	}
	domain := strings.ToLower(strings.TrimSpace(email[atIdx+1:]))
	_, found := disposableEmailDomains[domain]
	return found
}
